/**
 * Generated by Apache Royale Compiler from org/apache/royale/core/IContainerBaseStrandChildrenHost.as
 * org.apache.royale.core.IContainerBaseStrandChildrenHost
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('org.apache.royale.core.IContainerBaseStrandChildrenHost');
/* Royale Dependency List: org.apache.royale.core.IChild*/




/**
 * @interface
 */
org.apache.royale.core.IContainerBaseStrandChildrenHost = function() {
};
/**  * @type {number}
 */org.apache.royale.core.IContainerBaseStrandChildrenHost.prototype.$numElements;
/**
 * @param {org.apache.royale.core.IChild} c
 * @param {boolean=} dispatchEvent
 */
org.apache.royale.core.IContainerBaseStrandChildrenHost.prototype.$addElement = function(c, dispatchEvent) {
};
/**
 * @param {org.apache.royale.core.IChild} c
 * @param {number} index
 * @param {boolean=} dispatchEvent
 */
org.apache.royale.core.IContainerBaseStrandChildrenHost.prototype.$addElementAt = function(c, index, dispatchEvent) {
};
/**
 * @param {org.apache.royale.core.IChild} c
 * @param {boolean=} dispatchEvent
 */
org.apache.royale.core.IContainerBaseStrandChildrenHost.prototype.$removeElement = function(c, dispatchEvent) {
};
/**
 * @param {org.apache.royale.core.IChild} c
 * @return {number}
 */
org.apache.royale.core.IContainerBaseStrandChildrenHost.prototype.$getElementIndex = function(c) {
};
/**
 * @param {number} index
 * @return {org.apache.royale.core.IChild}
 */
org.apache.royale.core.IContainerBaseStrandChildrenHost.prototype.$getElementAt = function(index) {
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.core.IContainerBaseStrandChildrenHost.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'IContainerBaseStrandChildrenHost', qName: 'org.apache.royale.core.IContainerBaseStrandChildrenHost', kind: 'interface' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.core.IContainerBaseStrandChildrenHost.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    accessors: function () {
      return {
        '$numElements': { type: 'int', access: 'readonly', declaredBy: 'org.apache.royale.core.IContainerBaseStrandChildrenHost'}
      };
    },
    methods: function () {
      return {
        '$addElement': { type: 'void', declaredBy: 'org.apache.royale.core.IContainerBaseStrandChildrenHost', parameters: function () { return [ 'org.apache.royale.core.IChild', false ,'Boolean', true ]; }},
        '$addElementAt': { type: 'void', declaredBy: 'org.apache.royale.core.IContainerBaseStrandChildrenHost', parameters: function () { return [ 'org.apache.royale.core.IChild', false ,'int', false ,'Boolean', true ]; }},
        '$removeElement': { type: 'void', declaredBy: 'org.apache.royale.core.IContainerBaseStrandChildrenHost', parameters: function () { return [ 'org.apache.royale.core.IChild', false ,'Boolean', true ]; }},
        '$getElementIndex': { type: 'int', declaredBy: 'org.apache.royale.core.IContainerBaseStrandChildrenHost', parameters: function () { return [ 'org.apache.royale.core.IChild', false ]; }},
        '$getElementAt': { type: 'org.apache.royale.core.IChild', declaredBy: 'org.apache.royale.core.IContainerBaseStrandChildrenHost', parameters: function () { return [ 'int', false ]; }}
      };
    }
  };
};
/**
 * @const
 * @type {number}
 */
org.apache.royale.core.IContainerBaseStrandChildrenHost.prototype.ROYALE_COMPILE_FLAGS = 10;

//# sourceMappingURL=./IContainerBaseStrandChildrenHost.js.map
