/**
 * Generated by Apache Royale Compiler from org/apache/royale/core/IContainer.as
 * org.apache.royale.core.IContainer
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('org.apache.royale.core.IContainer');
/* Royale Dependency List: */

goog.require('org.apache.royale.core.IParent');



/**
 * @interface
 * @extends {org.apache.royale.core.IParent}
 */
org.apache.royale.core.IContainer = function() {
};
org.apache.royale.core.IContainer.prototype.childrenAdded = function() {
};
/**  * @type {org.apache.royale.core.IParent}
 */org.apache.royale.core.IContainer.prototype.strandChildren;


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.core.IContainer.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'IContainer', qName: 'org.apache.royale.core.IContainer', kind: 'interface' }], interfaces: [org.apache.royale.core.IParent] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.core.IContainer.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    accessors: function () {
      return {
        'strandChildren': { type: 'org.apache.royale.core.IParent', access: 'readonly', declaredBy: 'org.apache.royale.core.IContainer'}
      };
    },
    methods: function () {
      return {
        'childrenAdded': { type: 'void', declaredBy: 'org.apache.royale.core.IContainer'}
      };
    }
  };
};
/**
 * @const
 * @type {number}
 */
org.apache.royale.core.IContainer.prototype.ROYALE_COMPILE_FLAGS = 10;

//# sourceMappingURL=./IContainer.js.map
