/**
 * Generated by Apache Royale Compiler from org/apache/royale/core/IIndexedItemRenderer.as
 * org.apache.royale.core.IIndexedItemRenderer
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('org.apache.royale.core.IIndexedItemRenderer');
/* Royale Dependency List: */

goog.require('org.apache.royale.core.IItemRenderer');



/**
 * @interface
 * @extends {org.apache.royale.core.IItemRenderer}
 */
org.apache.royale.core.IIndexedItemRenderer = function() {
};
/**  * @type {number}
 */org.apache.royale.core.IIndexedItemRenderer.prototype.index;


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.core.IIndexedItemRenderer.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'IIndexedItemRenderer', qName: 'org.apache.royale.core.IIndexedItemRenderer', kind: 'interface' }], interfaces: [org.apache.royale.core.IItemRenderer] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.core.IIndexedItemRenderer.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    accessors: function () {
      return {
        'index': { type: 'int', access: 'readwrite', declaredBy: 'org.apache.royale.core.IIndexedItemRenderer'}
      };
    }
  };
};
/**
 * @const
 * @type {number}
 */
org.apache.royale.core.IIndexedItemRenderer.prototype.ROYALE_COMPILE_FLAGS = 10;

//# sourceMappingURL=./IIndexedItemRenderer.js.map
