/**
 * Generated by Apache Royale Compiler from org\apache\royale\core\IItemRendererParent.as
 * org.apache.royale.core.IItemRendererParent
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('org.apache.royale.core.IItemRendererParent');

goog.require('org.apache.royale.core.IParent');
goog.require('org.apache.royale.events.IEventDispatcher');



/**
 * @interface
 * @extends {org.apache.royale.core.IParent}
 * @extends {org.apache.royale.events.IEventDispatcher}
 */
org.apache.royale.core.IItemRendererParent = function() {
};


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('org.apache.royale.core.IItemRendererParent', org.apache.royale.core.IItemRendererParent);
org.apache.royale.core.IItemRendererParent.prototype.addItemRenderer = function(renderer) {
};
org.apache.royale.core.IItemRendererParent.prototype.addItemRendererAt = function(renderer, index) {
};
org.apache.royale.core.IItemRendererParent.prototype.removeItemRenderer = function(renderer) {
};
org.apache.royale.core.IItemRendererParent.prototype.getItemRendererForIndex = function(index) {
};
org.apache.royale.core.IItemRendererParent.prototype.removeAllItemRenderers = function() {
};
org.apache.royale.core.IItemRendererParent.prototype.updateAllItemRenderers = function() {
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.core.IItemRendererParent.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'IItemRendererParent', qName: 'org.apache.royale.core.IItemRendererParent', kind: 'interface' }], interfaces: [org.apache.royale.core.IParent, org.apache.royale.events.IEventDispatcher] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.core.IItemRendererParent.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    accessors: function () {return {};},
    methods: function () {
      return {
        'addItemRenderer': { type: 'void', declaredBy: 'org.apache.royale.core.IItemRendererParent', parameters: function () { return [  { index: 1, type: 'org.apache.royale.core.IItemRenderer', optional: false } ]; }},
        'addItemRendererAt': { type: 'void', declaredBy: 'org.apache.royale.core.IItemRendererParent', parameters: function () { return [  { index: 1, type: 'org.apache.royale.core.IItemRenderer', optional: false },{ index: 2, type: 'int', optional: false } ]; }},
        'removeItemRenderer': { type: 'void', declaredBy: 'org.apache.royale.core.IItemRendererParent', parameters: function () { return [  { index: 1, type: 'org.apache.royale.core.IItemRenderer', optional: false } ]; }},
        'getItemRendererForIndex': { type: 'org.apache.royale.core.IItemRenderer', declaredBy: 'org.apache.royale.core.IItemRendererParent', parameters: function () { return [  { index: 1, type: 'int', optional: false } ]; }},
        'removeAllItemRenderers': { type: 'void', declaredBy: 'org.apache.royale.core.IItemRendererParent'},
        'updateAllItemRenderers': { type: 'void', declaredBy: 'org.apache.royale.core.IItemRendererParent'}
      };
    }
  };
};