/**
 * Generated by Apache Royale Compiler from org\apache\royale\core\IItemRendererClassFactory.as
 * org.apache.royale.core.IItemRendererClassFactory
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('org.apache.royale.core.IItemRendererClassFactory');

goog.require('org.apache.royale.core.IBead');



/**
 * @interface
 * @extends {org.apache.royale.core.IBead}
 */
org.apache.royale.core.IItemRendererClassFactory = function() {
};


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('org.apache.royale.core.IItemRendererClassFactory', org.apache.royale.core.IItemRendererClassFactory);
org.apache.royale.core.IItemRendererClassFactory.prototype.createItemRenderer = function(parent) {
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.core.IItemRendererClassFactory.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'IItemRendererClassFactory', qName: 'org.apache.royale.core.IItemRendererClassFactory', kind: 'interface' }], interfaces: [org.apache.royale.core.IBead] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.core.IItemRendererClassFactory.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    accessors: function () {return {};},
    methods: function () {
      return {
        'createItemRenderer': { type: 'org.apache.royale.core.IItemRenderer', declaredBy: 'org.apache.royale.core.IItemRendererClassFactory', parameters: function () { return [  { index: 1, type: 'org.apache.royale.core.IItemRendererParent', optional: false } ]; }}
      };
    }
  };
};