/**
 * Generated by Apache Royale Compiler from org\apache\royale\core\IList.as
 * org.apache.royale.core.IList
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('org.apache.royale.core.IList');

goog.require('org.apache.royale.core.IItemRendererProvider');



/**
 * @interface
 * @extends {org.apache.royale.core.IItemRendererProvider}
 */
org.apache.royale.core.IList = function() {
};


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('org.apache.royale.core.IList', org.apache.royale.core.IList);
/**  * @type {org.apache.royale.core.IItemRendererParent}
 */org.apache.royale.core.IList.prototype.dataGroup;


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.core.IList.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'IList', qName: 'org.apache.royale.core.IList', kind: 'interface' }], interfaces: [org.apache.royale.core.IItemRendererProvider] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.core.IList.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    accessors: function () {
      return {
        'dataGroup': { type: 'org.apache.royale.core.IItemRendererParent', access: 'readonly', declaredBy: 'org.apache.royale.core.IList'}
      };
    },
    methods: function () {return {};}
  };
};