/**
 * Generated by Apache Royale Compiler from org/apache/royale/core/IRenderedObject.as
 * org.apache.royale.core.IRenderedObject
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('org.apache.royale.core.IRenderedObject');
/* Royale Dependency List: org.apache.royale.core.WrappedHTMLElement*/




/**
 * @interface
 */
org.apache.royale.core.IRenderedObject = function() {
};
/**  * @type {org.apache.royale.core.WrappedHTMLElement}
 */org.apache.royale.core.IRenderedObject.prototype.element;


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.core.IRenderedObject.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'IRenderedObject', qName: 'org.apache.royale.core.IRenderedObject', kind: 'interface' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.core.IRenderedObject.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    accessors: function () {
      return {
        'element': { type: 'org.apache.royale.core.WrappedHTMLElement', access: 'readonly', declaredBy: 'org.apache.royale.core.IRenderedObject'}
      };
    }
  };
};
/**
 * @const
 * @type {number}
 */
org.apache.royale.core.IRenderedObject.prototype.ROYALE_COMPILE_FLAGS = 10;

//# sourceMappingURL=./IRenderedObject.js.map
