/**
 * Generated by Apache Royale Compiler from org/apache/royale/core/IRoyaleElement.as
 * org.apache.royale.core.IRoyaleElement
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('org.apache.royale.core.IRoyaleElement');
/* Royale Dependency List: */



/**
 * @interface
 */
org.apache.royale.core.IRoyaleElement = function() {
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.core.IRoyaleElement.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'IRoyaleElement', qName: 'org.apache.royale.core.IRoyaleElement', kind: 'interface' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.core.IRoyaleElement.prototype.ROYALE_REFLECTION_INFO = function () {
  return {};
};
/**
 * @const
 * @type {number}
 */
org.apache.royale.core.IRoyaleElement.prototype.ROYALE_COMPILE_FLAGS = 10;

//# sourceMappingURL=./IRoyaleElement.js.map
