/**
 * Generated by Apache Royale Compiler from org\apache\royale\core\IStatesObject.as
 * org.apache.royale.core.IStatesObject
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('org.apache.royale.core.IStatesObject');

goog.require('org.apache.royale.events.IEventDispatcher');



/**
 * @interface
 * @extends {org.apache.royale.events.IEventDispatcher}
 */
org.apache.royale.core.IStatesObject = function() {
};


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('org.apache.royale.core.IStatesObject', org.apache.royale.core.IStatesObject);
/**  * @type {Array}
 */org.apache.royale.core.IStatesObject.prototype.states;


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.core.IStatesObject.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'IStatesObject', qName: 'org.apache.royale.core.IStatesObject', kind: 'interface' }], interfaces: [org.apache.royale.events.IEventDispatcher] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.core.IStatesObject.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    accessors: function () {
      return {
        'states': { type: 'Array', access: 'readonly', declaredBy: 'org.apache.royale.core.IStatesObject'},
        'currentState': { type: 'String', access: 'readwrite', declaredBy: 'org.apache.royale.core.IStatesObject'},
        'transitions': { type: 'Array', access: 'readonly', declaredBy: 'org.apache.royale.core.IStatesObject'}
      };
    },
    methods: function () {return {};}
  };
};