/**
 * Generated by Apache Royale Compiler from org/apache/royale/core/IStyleObject.as
 * org.apache.royale.core.IStyleObject
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('org.apache.royale.core.IStyleObject');
/* Royale Dependency List: org.apache.royale.core.IStyleableObject*/




/**
 * @interface
 */
org.apache.royale.core.IStyleObject = function() {
};
/**  * @type {org.apache.royale.core.IStyleableObject}
 */org.apache.royale.core.IStyleObject.prototype.object;


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.core.IStyleObject.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'IStyleObject', qName: 'org.apache.royale.core.IStyleObject', kind: 'interface' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.core.IStyleObject.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    accessors: function () {
      return {
        'object': { type: 'org.apache.royale.core.IStyleableObject', access: 'writeonly', declaredBy: 'org.apache.royale.core.IStyleObject'}
      };
    }
  };
};
/**
 * @const
 * @type {number}
 */
org.apache.royale.core.IStyleObject.prototype.ROYALE_COMPILE_FLAGS = 10;

//# sourceMappingURL=./IStyleObject.js.map
