/**
 * Generated by Apache Royale Compiler from org/apache/royale/core/ItemRendererOwnerViewBead.as
 * org.apache.royale.core.ItemRendererOwnerViewBead
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('org.apache.royale.core.ItemRendererOwnerViewBead');
/* Royale Dependency List: org.apache.royale.core.IItemRendererOwnerView*/

goog.require('org.apache.royale.core.Bead');



/**
 *  Constructor.
 *  
 *  @langversion 3.0
 *  @playerversion Flash 10.2
 *  @playerversion AIR 2.6
 *  @productversion Royale 0.0
 * @constructor
 * @extends {org.apache.royale.core.Bead}
 * @param {org.apache.royale.core.IItemRendererOwnerView} ownerView
 */
org.apache.royale.core.ItemRendererOwnerViewBead = function(ownerView) {
  org.apache.royale.core.ItemRendererOwnerViewBead.base(this, 'constructor');
  this.ownerView = ownerView;
};
goog.inherits(org.apache.royale.core.ItemRendererOwnerViewBead, org.apache.royale.core.Bead);


/**
 * @type {org.apache.royale.core.IItemRendererOwnerView}
 */
org.apache.royale.core.ItemRendererOwnerViewBead.prototype.ownerView;


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.core.ItemRendererOwnerViewBead.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'ItemRendererOwnerViewBead', qName: 'org.apache.royale.core.ItemRendererOwnerViewBead', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.core.ItemRendererOwnerViewBead.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {
      return {
        'ownerView': { type: 'org.apache.royale.core.IItemRendererOwnerView', get_set: function (/** org.apache.royale.core.ItemRendererOwnerViewBead */ inst, /** * */ v) {return v !== undefined ? inst.ownerView = v : inst.ownerView;}}
      };
    },
    methods: function () {
      return {
        'ItemRendererOwnerViewBead': { type: '', declaredBy: 'org.apache.royale.core.ItemRendererOwnerViewBead', parameters: function () { return [ 'org.apache.royale.core.IItemRendererOwnerView', false ]; }}
      };
    }
  };
};
/**
 * @const
 * @type {number}
 */
org.apache.royale.core.ItemRendererOwnerViewBead.prototype.ROYALE_COMPILE_FLAGS = 10;

//# sourceMappingURL=./ItemRendererOwnerViewBead.js.map
