/**
 * Generated by Apache Royale Compiler from org\apache\royale\core\IViewportModel.as
 * org.apache.royale.core.IViewportModel
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('org.apache.royale.core.IViewportModel');

goog.require('org.apache.royale.core.IBead');



/**
 * @interface
 * @extends {org.apache.royale.core.IBead}
 */
org.apache.royale.core.IViewportModel = function() {
};


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('org.apache.royale.core.IViewportModel', org.apache.royale.core.IViewportModel);
/**  * @type {org.apache.royale.geom.Rectangle}
 */org.apache.royale.core.IViewportModel.prototype.borderMetrics;


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.core.IViewportModel.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'IViewportModel', qName: 'org.apache.royale.core.IViewportModel', kind: 'interface' }], interfaces: [org.apache.royale.core.IBead] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.core.IViewportModel.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    accessors: function () {
      return {
        'borderMetrics': { type: 'org.apache.royale.geom.Rectangle', access: 'readwrite', declaredBy: 'org.apache.royale.core.IViewportModel'},
        'chromeMetrics': { type: 'org.apache.royale.geom.Rectangle', access: 'readwrite', declaredBy: 'org.apache.royale.core.IViewportModel'}
      };
    },
    methods: function () {return {};}
  };
};