/**
 * Generated by Apache Royale Compiler from org\apache\royale\core\SimpleCSSStylesWithFlex.as
 * org.apache.royale.core.SimpleCSSStylesWithFlex
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('org.apache.royale.core.SimpleCSSStylesWithFlex');



/**
 *  Constructor.
 *  
 *  @langversion 3.0
 *  @playerversion Flash 10.2
 *  @playerversion AIR 2.6
 *  @productversion Royale 0.0
 * @constructor
 */
org.apache.royale.core.SimpleCSSStylesWithFlex = function() {
  
  this.styleList = {"top":1, "bottom":1, "left":1, "right":1, "padding":1, "paddingLeft":1, "paddingRight":1, "paddingTop":1, "paddingBottom":1, "margin":1, "marginLeft":1, "marginRight":1, "marginTop":1, "marginBottom":1, "verticalAlign":1, "fontFamily":1, "fontSize":1, "color":1, "fontWeight":1, "fontStyle":1, "backgroundColor":1, "backgroundImage":1, "borderColor":1, "borderStyle":1, "borderRadius":1, "borderWidth":1, "flexGrow":1, "flexShrink":1, "order":1};
  ;
};


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('org.apache.royale.core.SimpleCSSStylesWithFlex', org.apache.royale.core.SimpleCSSStylesWithFlex);


/**
 * @export
 * @type {Object}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.styleList;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.top;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.bottom;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.left;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.right;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.padding;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.paddingLeft;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.paddingRight;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.paddingTop;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.paddingBottom;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.margin;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.marginLeft;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.marginRight;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.marginTop;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.marginBottom;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.verticalAlign;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.fontFamily;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.fontSize;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.color;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.fontWeight;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.fontStyle;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.backgroundColor;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.backgroundImage;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.borderColor;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.borderStyle;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.borderRadius;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.borderWidth;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.flexGrow;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.flexShrink;


/**
 * @export
 * @type {*}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.order;


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'SimpleCSSStylesWithFlex', qName: 'org.apache.royale.core.SimpleCSSStylesWithFlex', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.core.SimpleCSSStylesWithFlex.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {
      return {
        'styleList': { type: 'Object'},
        'top': { type: '*'},
        'bottom': { type: '*'},
        'left': { type: '*'},
        'right': { type: '*'},
        'padding': { type: '*'},
        'paddingLeft': { type: '*'},
        'paddingRight': { type: '*'},
        'paddingTop': { type: '*'},
        'paddingBottom': { type: '*'},
        'margin': { type: '*'},
        'marginLeft': { type: '*'},
        'marginRight': { type: '*'},
        'marginTop': { type: '*'},
        'marginBottom': { type: '*'},
        'verticalAlign': { type: '*'},
        'fontFamily': { type: '*'},
        'fontSize': { type: '*'},
        'color': { type: '*'},
        'fontWeight': { type: '*'},
        'fontStyle': { type: '*'},
        'backgroundColor': { type: '*'},
        'backgroundImage': { type: '*'},
        'borderColor': { type: '*'},
        'borderStyle': { type: '*'},
        'borderRadius': { type: '*'},
        'borderWidth': { type: '*'},
        'flexGrow': { type: '*'},
        'flexShrink': { type: '*'},
        'order': { type: '*'}
      };
    },
    accessors: function () {return {};},
    methods: function () {
      return {
        'SimpleCSSStylesWithFlex': { type: '', declaredBy: 'org.apache.royale.core.SimpleCSSStylesWithFlex'}
      };
    }
  };
};