/**
 * Generated by Apache Royale Compiler from org\apache\royale\net\HTTPHeader.as
 * org.apache.royale.net.HTTPHeader
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('org.apache.royale.net.HTTPHeader');



/**
 *  Constructor.
 *  
 *  @asparam name The name of the header.
 *  @asparam value The value for that header.
 * 
 *  @langversion 3.0
 *  @playerversion Flash 10.2
 *  @playerversion AIR 2.6
 *  @productversion Royale 0.0
 * @constructor
 * @param {string=} name
 * @param {string=} value
 */
org.apache.royale.net.HTTPHeader = function(name, value) {
  name = typeof name !== 'undefined' ? name : null;
  value = typeof value !== 'undefined' ? value : null;
  ;
  this.name = name;
  this.value = value;
};


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('org.apache.royale.net.HTTPHeader', org.apache.royale.net.HTTPHeader);


/**
 * @export
 * @const
 * @type {string}
 */
org.apache.royale.net.HTTPHeader.CONTENT_TYPE = "Content-type";


/**
 * @export
 * @const
 * @type {string}
 */
org.apache.royale.net.HTTPHeader.CONTENT_LENGTH = "Content-length";


/**
 * @export
 * @const
 * @type {string}
 */
org.apache.royale.net.HTTPHeader.CONNECTION = "Connection";


/**
 * @export
 * @type {string}
 */
org.apache.royale.net.HTTPHeader.prototype.name;


/**
 * @export
 * @type {string}
 */
org.apache.royale.net.HTTPHeader.prototype.value;


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.net.HTTPHeader.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'HTTPHeader', qName: 'org.apache.royale.net.HTTPHeader', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.net.HTTPHeader.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {
      return {
        'name': { type: 'String'},
        'value': { type: 'String'}
      };
    },
    accessors: function () {return {};},
    methods: function () {
      return {
        'HTTPHeader': { type: '', declaredBy: 'org.apache.royale.net.HTTPHeader', parameters: function () { return [  { index: 1, type: 'String', optional: true },{ index: 2, type: 'String', optional: true } ]; }}
      };
    }
  };
};