/**
 * Generated by Apache Royale Compiler from org\apache\royale\net\HTTPServiceBase.as
 * org.apache.royale.net.HTTPServiceBase
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('org.apache.royale.net.HTTPServiceBase');

goog.require('org.apache.royale.core.ElementWrapper');



/**
 * @constructor
 * @extends {org.apache.royale.core.ElementWrapper}
 */
org.apache.royale.net.HTTPServiceBase = function() {
  org.apache.royale.net.HTTPServiceBase.base(this, 'constructor');
};
goog.inherits(org.apache.royale.net.HTTPServiceBase, org.apache.royale.core.ElementWrapper);


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('org.apache.royale.net.HTTPServiceBase', org.apache.royale.net.HTTPServiceBase);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.net.HTTPServiceBase.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'HTTPServiceBase', qName: 'org.apache.royale.net.HTTPServiceBase', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.net.HTTPServiceBase.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {return {};},
    methods: function () {return {};}
  };
};