/**
 * Generated by Apache Royale Compiler from org/apache/royale/reflection/nativejs/AS3Number.as
 * org.apache.royale.reflection.nativejs.AS3Number
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('org.apache.royale.reflection.nativejs.AS3Number');
/* Royale Dependency List: */
goog.provide('org.apache.royale.reflection.nativejs.AS3Number.singleton');



/**
 * Provides data for a stand-in TypeDefinition of the native as3 type for javascript
 * @return {Object}
 */
org.apache.royale.reflection.nativejs.AS3Number = function() {
  if (org.apache.royale.reflection.nativejs.AS3Number.singleton)
    return org.apache.royale.reflection.nativejs.AS3Number.singleton;
  var /** @type {Object} */ ret = {};
  ret['classRef'] = Number;
  ret['name'] = 'Number';
  ret['NATIVE_TYPE'] = true;
  ret['NATIVE_BASE'] = Object;
  ret['ROYALE_CLASS_INFO'] = {names:[{name:'Number', qName:'Number', kind:'class'}]};
  ret['ROYALE_REFLECTION_INFO'] = function() {
    return {'methods':function() {
      return {'Number':{'parameters':function() {
        return ['*', true];
      }, 'type':'', 'declaredBy':'Number'}, '|sin':{'parameters':function() {
        return ['Number', false];
      }, 'declaredBy':'Number', 'type':'Number'}, '|random':{'declaredBy':'Number', 'type':'Number'}, '|atan2':{'parameters':function() {
        return ['Number', false, {'index':2, 'optional':false, 'type':'Number'}];
      }, 'declaredBy':'Number', 'type':'Number'}, '|sqrt':{'parameters':function() {
        return ['Number', false];
      }, 'declaredBy':'Number', 'type':'Number'}, '|cos':{'parameters':function() {
        return ['Number', false];
      }, 'declaredBy':'Number', 'type':'Number'}, '|asin':{'parameters':function() {
        return ['Number', false];
      }, 'declaredBy':'Number', 'type':'Number'}, '|tan':{'parameters':function() {
        return ['Number', false];
      }, 'declaredBy':'Number', 'type':'Number'}, '|floor':{'parameters':function() {
        return ['Number', false];
      }, 'declaredBy':'Number', 'type':'Number'}, '|max':{'parameters':function() {
        return ['Number', true, 'Number', true];
      }, 'declaredBy':'Number', 'type':'Number'}, '|abs':{'parameters':function() {
        return ['Number', false];
      }, 'declaredBy':'Number', 'type':'Number'}, '|exp':{'parameters':function() {
        return ['Number', false];
      }, 'declaredBy':'Number', 'type':'Number'}, '|atan':{'parameters':function() {
        return ['Number', false];
      }, 'declaredBy':'Number', 'type':'Number'}, '|round':{'parameters':function() {
        return ['Number', false];
      }, 'declaredBy':'Number', 'type':'Number'}, '|log':{'parameters':function() {
        return ['Number', false];
      }, 'declaredBy':'Number', 'type':'Number'}, '|min':{'parameters':function() {
        return ['Number', true, 'Number', true];
      }, 'declaredBy':'Number', 'type':'Number'}, '|acos':{'parameters':function() {
        return ['Number', false];
      }, 'declaredBy':'Number', 'type':'Number'}, '|ceil':{'parameters':function() {
        return ['Number', false];
      }, 'declaredBy':'Number', 'type':'Number'}, '|pow':{'parameters':function() {
        return ['Number', false, {'index':2, 'optional':false, 'type':'Number'}];
      }, 'declaredBy':'Number', 'type':'Number'}};
    }};
  };
  org.apache.royale.reflection.nativejs.AS3Number.singleton = ret;
  return ret;
}


/**
 * @package
 * @type {*}
 */
org.apache.royale.reflection.nativejs.AS3Number.singleton = null
