/**
 * Generated by Apache Royale Compiler from org/apache/royale/reflection/nativejs/AS3Object.as
 * org.apache.royale.reflection.nativejs.AS3Object
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('org.apache.royale.reflection.nativejs.AS3Object');
/* Royale Dependency List: */
goog.provide('org.apache.royale.reflection.nativejs.AS3Object.singleton');



/**
 * Provides data for a stand-in TypeDefinition of the native as3 type for javascript
 * @return {Object}
 */
org.apache.royale.reflection.nativejs.AS3Object = function() {
  if (org.apache.royale.reflection.nativejs.AS3Object.singleton)
    return org.apache.royale.reflection.nativejs.AS3Object.singleton;
  var /** @type {Object} */ ret = {};
  ret['classRef'] = Object;
  ret['name'] = 'Object';
  ret['NATIVE_TYPE'] = true;
  ret['ROYALE_CLASS_INFO'] = {names:[{name:'Object', qName:'Object', kind:'class', isDynamic:true}]};
  ret['ROYALE_REFLECTION_INFO'] = function() {
    return {'accessors':function() {
      return {'length':{'access':'readwrite', 'type':'uint', 'declaredBy':'Object'}};
    }, 'methods':function() {
      return {'Object':{'declaredBy':'Object', 'type':''}};
    }};
  };
  org.apache.royale.reflection.nativejs.AS3Object.singleton = ret;
  return ret;
}


/**
 * @package
 * @type {*}
 */
org.apache.royale.reflection.nativejs.AS3Object.singleton = null
