/**
 * Generated by Apache Royale Compiler from org/apache/royale/utils/string/InternalSafeHtml.as
 * org.apache.royale.utils.string.InternalSafeHtml
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('org.apache.royale.utils.string.InternalSafeHtml');
/* Royale Dependency List: */



/**
 * @constructor
 * @extends {goog.html.SafeHtml}
 */
org.apache.royale.utils.string.InternalSafeHtml = function() {
  org.apache.royale.utils.string.InternalSafeHtml.base(this, 'constructor');
};
goog.inherits(org.apache.royale.utils.string.InternalSafeHtml, goog.html.SafeHtml);


/**
 * @nocollapse
 * @param {goog.html.SafeHtml} safeHtml
 * @return {string}
 */
org.apache.royale.utils.string.InternalSafeHtml.unwrap = function(safeHtml) {
  return goog.html.SafeHtml.unwrap(safeHtml);
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.utils.string.InternalSafeHtml.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'InternalSafeHtml', qName: 'org.apache.royale.utils.string.InternalSafeHtml', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.utils.string.InternalSafeHtml.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    methods: function () {
      return {
        'InternalSafeHtml': { type: '', declaredBy: 'org.apache.royale.utils.string.InternalSafeHtml'},
        '|unwrap': { type: 'String', declaredBy: 'org.apache.royale.utils.string.InternalSafeHtml', parameters: function () { return [ 'goog.html.SafeHtml', false ]; }}
      };
    }
  };
};
/**
 * @const
 * @type {number}
 */
org.apache.royale.utils.string.InternalSafeHtml.prototype.ROYALE_COMPILE_FLAGS = 10;

//# sourceMappingURL=./InternalSafeHtml.js.map
