/**
 * Generated by Apache Royale Compiler from ASDocClassAttribute.as
 * ASDocClassAttribute
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('ASDocClassAttribute');
/* Royale Dependency List: */

goog.require('org.apache.royale.events.EventDispatcher');



/**
 * @constructor
 * @extends {org.apache.royale.events.EventDispatcher}
 */
ASDocClassAttribute = function() {// Compiler generated Binding support implementation:
ASDocClassAttribute.base(this, 'constructor');

};
// Compiler generated Binding support implementation:
goog.inherits(ASDocClassAttribute, org.apache.royale.events.EventDispatcher);


/**
 * @private
 * @type {string}
 */
ASDocClassAttribute.prototype.ASDocClassAttribute__name = null;


/**
 * @private
 * @type {string}
 */
ASDocClassAttribute.prototype.ASDocClassAttribute__value = null;


/**
 * @nocollapse
 * @export
 * @type {string}
 */
ASDocClassAttribute.prototype.name;


ASDocClassAttribute.prototype.get__name = function() {
return this.ASDocClassAttribute__name;
};


ASDocClassAttribute.prototype.set__name = function(__v__) {
this.ASDocClassAttribute__name = __v__;
};


/**
 * @nocollapse
 * @export
 * @type {string}
 */
ASDocClassAttribute.prototype.value;


ASDocClassAttribute.prototype.get__value = function() {
return this.ASDocClassAttribute__value;
};


ASDocClassAttribute.prototype.set__value = function(__v__) {
this.ASDocClassAttribute__value = __v__;
};


Object.defineProperties(ASDocClassAttribute.prototype, /** @lends {ASDocClassAttribute.prototype} */ {
/**
 * @type {string}
 */
name: {
get: ASDocClassAttribute.prototype.get__name,
set: ASDocClassAttribute.prototype.set__name},
/**
 * @type {string}
 */
value: {
get: ASDocClassAttribute.prototype.get__value,
set: ASDocClassAttribute.prototype.set__value}}
);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
ASDocClassAttribute.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'ASDocClassAttribute', qName: 'ASDocClassAttribute', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
ASDocClassAttribute.prototype.ROYALE_REFLECTION_INFO = function () {
return {
  accessors: function () {
    return {
      'name': { type: 'String', access: 'readwrite', declaredBy: 'ASDocClassAttribute'},
      'value': { type: 'String', access: 'readwrite', declaredBy: 'ASDocClassAttribute'}
    };
  }
};
};
/**
 * @const
 * @type {number}
 */
ASDocClassAttribute.prototype.ROYALE_COMPILE_FLAGS = 9;
