/**
 * Generated by Apache Royale Compiler from ASDocClassTags.as
 * ASDocClassTags
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('ASDocClassTags');
/* Royale Dependency List: */

goog.require('org.apache.royale.events.EventDispatcher');



/**
 * @constructor
 * @extends {org.apache.royale.events.EventDispatcher}
 */
ASDocClassTags = function() {// Compiler generated Binding support implementation:
ASDocClassTags.base(this, 'constructor');

};
// Compiler generated Binding support implementation:
goog.inherits(ASDocClassTags, org.apache.royale.events.EventDispatcher);


/**
 * @nocollapse
 * @const
 * @type {string}
 */
ASDocClassTags.key = "tagName:string;values:object";


/**
 * @private
 * @type {string}
 */
ASDocClassTags.prototype.ASDocClassTags__tagName = null;


/**
 * @private
 * @type {Array}
 */
ASDocClassTags.prototype.ASDocClassTags__values = null;


/**
 * @nocollapse
 * @export
 * @type {string}
 */
ASDocClassTags.prototype.tagName;


ASDocClassTags.prototype.get__tagName = function() {
return this.ASDocClassTags__tagName;
};


ASDocClassTags.prototype.set__tagName = function(__v__) {
this.ASDocClassTags__tagName = __v__;
};


/**
 * @nocollapse
 * @export
 * @type {Array}
 */
ASDocClassTags.prototype.values;


ASDocClassTags.prototype.get__values = function() {
return this.ASDocClassTags__values;
};


ASDocClassTags.prototype.set__values = function(__v__) {
this.ASDocClassTags__values = __v__;
};


Object.defineProperties(ASDocClassTags.prototype, /** @lends {ASDocClassTags.prototype} */ {
/**
 * @type {string}
 */
tagName: {
get: ASDocClassTags.prototype.get__tagName,
set: ASDocClassTags.prototype.set__tagName},
/**
 * @type {Array}
 */
values: {
get: ASDocClassTags.prototype.get__values,
set: ASDocClassTags.prototype.set__values}}
);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
ASDocClassTags.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'ASDocClassTags', qName: 'ASDocClassTags', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
ASDocClassTags.prototype.ROYALE_REFLECTION_INFO = function () {
return {
  accessors: function () {
    return {
      'tagName': { type: 'String', access: 'readwrite', declaredBy: 'ASDocClassTags'},
      'values': { type: 'Array', access: 'readwrite', declaredBy: 'ASDocClassTags'}
    };
  }
};
};
/**
 * @const
 * @type {number}
 */
ASDocClassTags.prototype.ROYALE_COMPILE_FLAGS = 9;
/**
 * Provide reflection support for distinguishing dynamic fields on class object (static)
 * @const
 * @type {Array<string>}
 */
ASDocClassTags.prototype.ROYALE_INITIAL_STATICS = Object.keys(ASDocClassTags);
