/**
 * Generated by Apache Royale Compiler from ClassPickerHashAnchorStringItemRenderer.as
 * ClassPickerHashAnchorStringItemRenderer
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('ClassPickerHashAnchorStringItemRenderer');

goog.require('org.apache.royale.html.supportClasses.StringItemRenderer');



/**
 *  constructor.
 *
 *  @langversion 3.0
 *  @playerversion Flash 10.2
 *  @playerversion AIR 2.6
 *  @productversion Royale 0.0
 * @constructor
 * @extends {org.apache.royale.html.supportClasses.StringItemRenderer}
 */
ClassPickerHashAnchorStringItemRenderer = function() {
  ClassPickerHashAnchorStringItemRenderer.base(this, 'constructor');
  this.typeNames += " HashAnchorStringItemRenderer";
};
goog.inherits(ClassPickerHashAnchorStringItemRenderer, org.apache.royale.html.supportClasses.StringItemRenderer);


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('ClassPickerHashAnchorStringItemRenderer', ClassPickerHashAnchorStringItemRenderer);


ClassPickerHashAnchorStringItemRenderer.prototype.set__text = function(value) {
  
  var /** @type {string} */ pkg = "";
  var /** @type {string} */ cname = value;
  var /** @type {string} */ href = value;
  var /** @type {number} */ c = href.lastIndexOf(".");
  if (c != -1) {
    pkg = href.substr(0, c);
    cname = href.substr(c + 1);
    href = pkg + "/" + cname;
  } else {
    href = "/" + cname;
  }
  this.element.innerHTML = "<a href='#!" + href + "' class='HashAnchorAnchor'>" + value + "</a>";
};


Object.defineProperties(ClassPickerHashAnchorStringItemRenderer.prototype, /** @lends {ClassPickerHashAnchorStringItemRenderer.prototype} */ {
/**
  * @export
  * @type {string} */
text: {
get: org.apache.royale.html.supportClasses.StringItemRenderer.prototype.get__text,
set: ClassPickerHashAnchorStringItemRenderer.prototype.set__text}}
);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
ClassPickerHashAnchorStringItemRenderer.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'ClassPickerHashAnchorStringItemRenderer', qName: 'ClassPickerHashAnchorStringItemRenderer', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
ClassPickerHashAnchorStringItemRenderer.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {
      return {
        'text': { type: 'String', access: 'writeonly', declaredBy: 'ClassPickerHashAnchorStringItemRenderer'}
      };
    },
    methods: function () {
      return {
        'ClassPickerHashAnchorStringItemRenderer': { type: '', declaredBy: 'ClassPickerHashAnchorStringItemRenderer'}
      };
    }
  };
};