/**
 * Generated by Apache Royale Compiler from EventSummaryRenderer.mxml
 * EventSummaryRenderer
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('EventSummaryRenderer');

goog.require('org.apache.royale.html.supportClasses.MXMLItemRenderer');
goog.require('org.apache.royale.html.beads.layouts.VerticalLayout');
goog.require('org.apache.royale.binding.ItemRendererDataBinding');
goog.require('org.apache.royale.html.Group');
goog.require('org.apache.royale.html.beads.layouts.HorizontalLayout');
goog.require('org.apache.royale.html.elements.A');
goog.require('org.apache.royale.html.Label');
goog.require('org.apache.royale.html.supportClasses.UIItemRendererBase');



/**
 * @constructor
 * @extends {org.apache.royale.html.supportClasses.MXMLItemRenderer}
 */
EventSummaryRenderer = function() {
  EventSummaryRenderer.base(this, 'constructor');
  
  /**
   * @private
   * @type {org.apache.royale.html.beads.layouts.VerticalLayout}
   */
  this.$ID0_;
  
  /**
   * @private
   * @type {org.apache.royale.binding.ItemRendererDataBinding}
   */
  this.$ID1_;
  
  /**
   * @private
   * @type {org.apache.royale.html.Group}
   */
  this.typeGroup_;
  
  /**
   * @private
   * @type {org.apache.royale.html.beads.layouts.HorizontalLayout}
   */
  this.$ID2_;
  
  /**
   * @private
   * @type {org.apache.royale.html.elements.A}
   */
  this.qname_;
  
  /**
   * @private
   * @type {org.apache.royale.html.Label}
   */
  this.label_;
  
  /**
   * @private
   * @type {Array}
   */
  this.mxmldd;
  
  /**
   * @private
   * @type {Array}
   */
  this.mxmldp;

  this.generateMXMLAttributes
  ([3,
'className',
true,
'summary',
'percentWidth',
true,
100.0,
'beads',
null, [org.apache.royale.html.beads.layouts.VerticalLayout, 1, '_id', true, '$ID0', 0, 0, null, org.apache.royale.binding.ItemRendererDataBinding, 1, '_id', true, '$ID1', 0, 0, null],
0,
0
  ]);
  
};
goog.inherits(EventSummaryRenderer, org.apache.royale.html.supportClasses.MXMLItemRenderer);


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('EventSummaryRenderer', EventSummaryRenderer);



/**
 * @private
 * @type {string}
 */
EventSummaryRenderer.prototype._color0 = "#fff";


;


;


/**
 * @private
 * @type {string}
 */
EventSummaryRenderer.prototype._color1 = "#ffeeee";


;


;


;


;


/**
 * @private
 * @type {boolean}
 */
EventSummaryRenderer.prototype.oddIndex;


/**
 * @export
 * @override
 */
EventSummaryRenderer.prototype.addedToParent = function() {
  EventSummaryRenderer.superClass_.addedToParent.apply(this);
  var /** @type {number} */ index = this.parent.getElementIndex(this);
  this.oddIndex = ((index % 2) == 1);
  this.element.style.backgroundColor = this.oddIndex ? this._color1 : this._color0;
};


/**
 * @asprivate
 * @export
 * @override
 */
EventSummaryRenderer.prototype.updateRenderer = function() {
  EventSummaryRenderer.superClass_.updateRenderer.apply(this);
  if (this.element.style.backgroundColor == null || this.element.style.backgroundColor == "")
    this.element.style.backgroundColor = this.oddIndex ? this._color1 : this._color0;
};





EventSummaryRenderer.prototype.get__backgroundColor0 = function() {
  return this._color0;
};


EventSummaryRenderer.prototype.set__backgroundColor0 = function(value) {
  this._color0 = value;
};


EventSummaryRenderer.prototype.get__backgroundColor1 = function() {
  return this._color1;
};


EventSummaryRenderer.prototype.set__backgroundColor1 = function(value) {
  this._color1 = value;
};


EventSummaryRenderer.prototype.set__data = function(value) {
  EventSummaryRenderer.superClass_.set__data.apply(this, [ value] );
  this.qname.href = "#!" + this.obj.ownerhref + "/" + this.obj.qname;
};


EventSummaryRenderer.prototype.get__obj = function() {
  return this.data;
};


Object.defineProperties(EventSummaryRenderer.prototype, /** @lends {EventSummaryRenderer.prototype} */ {
/**
  * @export
  * @type {string} */
backgroundColor0: {
get: EventSummaryRenderer.prototype.get__backgroundColor0,
set: EventSummaryRenderer.prototype.set__backgroundColor0},
/**
  * @export
  * @type {string} */
backgroundColor1: {
get: EventSummaryRenderer.prototype.get__backgroundColor1,
set: EventSummaryRenderer.prototype.set__backgroundColor1},
/**
  * @export
  * @type {Object} */
data: {
get: org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.get__data,
set: EventSummaryRenderer.prototype.set__data},
/**
  * @export
  * @type {valueObjects.ValueObject} */
obj: {
get: EventSummaryRenderer.prototype.get__obj}}
);Object.defineProperties(EventSummaryRenderer.prototype, /** @lends {EventSummaryRenderer.prototype} */ {
/** @export */
    typeGroup: {
    /** @this {EventSummaryRenderer} */
    get: function() {
      return this.typeGroup_;
    },
    /** @this {EventSummaryRenderer} */
    set: function(value) {
      if (value != this.typeGroup_) {
        this.typeGroup_ = value;
        this.dispatchEvent(org.apache.royale.events.ValueChangeEvent.createUpdateEvent(this, 'typeGroup', null, value));
      }
    }
  },
  /** @export */
    qname: {
    /** @this {EventSummaryRenderer} */
    get: function() {
      return this.qname_;
    },
    /** @this {EventSummaryRenderer} */
    set: function(value) {
      if (value != this.qname_) {
        this.qname_ = value;
        this.dispatchEvent(org.apache.royale.events.ValueChangeEvent.createUpdateEvent(this, 'qname', null, value));
      }
    }
  },
  /** @export */
    label: {
    /** @this {EventSummaryRenderer} */
    get: function() {
      return this.label_;
    },
    /** @this {EventSummaryRenderer} */
    set: function(value) {
      if (value != this.label_) {
        this.label_ = value;
        this.dispatchEvent(org.apache.royale.events.ValueChangeEvent.createUpdateEvent(this, 'label', null, value));
      }
    }
  },
  'MXMLDescriptor': {
    /** @this {EventSummaryRenderer} */
    get: function() {
      {
        if (this.mxmldd == undefined)
        {
          /** @type {Array} */
          var arr = EventSummaryRenderer.superClass_.get__MXMLDescriptor.apply(this);
          /** @type {Array} */
          var data = [
      org.apache.royale.html.Group,
2,
'id',
true,
'typeGroup',
'beads',
null, [org.apache.royale.html.beads.layouts.HorizontalLayout, 1, '_id', true, '$ID2', 0, 0, null],
0,
0,
[org.apache.royale.html.elements.A, 2, 'id', true, 'qname', 'className', true, 'eventSummaryQName', 0, 0, null, org.apache.royale.html.Label, 2, 'id', true, 'label', 'className', true, 'eventDescription', 0, 0, null]
      ];
        
          if (arr)
            this.mxmldd = arr.concat(data);
          else
            this.mxmldd = data;
        }
        return this.mxmldd;
      }
      }
    }
  });
  /**
   * @export
   */
  EventSummaryRenderer.prototype._bindings = [
  2,
  ["data", "qname"],
  null,
  ["qname", "text"],
  ["data", "shortDescription"],
  null,
  ["label", "text"],
  0,
  2,
  "data",
  ["dataChange","__NoChangeEvent__"],
  [0,1],
  null,
  [
  1,
  2,
  "qname",
  "valueChange",
  0,
  null,
  null,
  2,
  2,
  "shortDescription",
  "valueChange",
  1,
  null,
  null,
  null]];
  /**
   * Metadata
   *
   * @type {Object.<string, Array.<Object>>}
   */
  EventSummaryRenderer.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'EventSummaryRenderer', qName: 'EventSummaryRenderer', kind: 'class'  }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
EventSummaryRenderer.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {
      return {
        'backgroundColor0': { type: 'String', access: 'readwrite', declaredBy: 'EventSummaryRenderer'},
        'backgroundColor1': { type: 'String', access: 'readwrite', declaredBy: 'EventSummaryRenderer'},
        'data': { type: 'Object', access: 'writeonly', declaredBy: 'EventSummaryRenderer'},
        'obj': { type: 'valueObjects.ValueObject', access: 'readonly', declaredBy: 'EventSummaryRenderer', metadata: function () { return [  ]; }},
        'typeGroup': { type: 'org.apache.royale.html.Group', access: 'readwrite', declaredBy: 'EventSummaryRenderer'},
        'qname': { type: 'org.apache.royale.html.elements.A', access: 'readwrite', declaredBy: 'EventSummaryRenderer'},
        'label': { type: 'org.apache.royale.html.Label', access: 'readwrite', declaredBy: 'EventSummaryRenderer'}
      };
    },
    methods: function () {
      return {
        'addedToParent': { type: 'void', declaredBy: 'EventSummaryRenderer'},
        'updateRenderer': { type: 'void', declaredBy: 'EventSummaryRenderer'},
        'EventSummaryRenderer': { type: '', declaredBy: 'EventSummaryRenderer'}
      };
    }
  };
};

  
  