/**
 * Generated by Apache Royale Compiler from MethodDetailRenderer.mxml
 * MethodDetailRenderer
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('MethodDetailRenderer');
/* Royale Dependency List: org.apache.royale.html.beads.layouts.VerticalFlexLayout,org.apache.royale.binding.ItemRendererDataBinding,org.apache.royale.html.Group,org.apache.royale.html.beads.layouts.HorizontalLayout,org.apache.royale.html.Label,org.apache.royale.html.DataContainer,org.apache.royale.html.beads.models.ListPresentationModel,org.apache.royale.html.elements.A,org.apache.royale.html.MultilineLabel,AttributeRenderer,ParameterRenderer,org.apache.royale.core.ClassFactory,org.apache.royale.utils.string.sanitizeHtml,org.apache.royale.html.supportClasses.UIItemRendererBase*/

goog.require('org.apache.royale.html.supportClasses.MXMLItemRenderer');



/**
 * @constructor
 * @extends {org.apache.royale.html.supportClasses.MXMLItemRenderer}
 */
MethodDetailRenderer = function() {
  MethodDetailRenderer.base(this, 'constructor');
  
  /**
   * @private
   * @type {org.apache.royale.html.beads.layouts.VerticalFlexLayout}
   */
  this.$ID_10_0;
  
  /**
   * @private
   * @type {org.apache.royale.binding.ItemRendererDataBinding}
   */
  this.$ID_10_1;
  
  /**
   * @private
   * @type {org.apache.royale.html.Group}
   */
  this.$ID_10_4;
  
  /**
   * @private
   * @type {org.apache.royale.html.beads.layouts.HorizontalLayout}
   */
  this.$ID_10_2;
  
  /**
   * @private
   * @type {org.apache.royale.html.Label}
   */
  this.target_;
  
  /**
   * @private
   * @type {org.apache.royale.html.Label}
   */
  this.$ID_10_3;
  
  /**
   * @private
   * @type {org.apache.royale.html.Group}
   */
  this.propertyTypeGroup_;
  
  /**
   * @private
   * @type {org.apache.royale.html.beads.layouts.HorizontalLayout}
   */
  this.$ID_10_5;
  
  /**
   * @private
   * @type {org.apache.royale.html.Label}
   */
  this.$ID_10_6;
  
  /**
   * @private
   * @type {org.apache.royale.html.Label}
   */
  this.$ID_10_7;
  
  /**
   * @private
   * @type {org.apache.royale.html.DataContainer}
   */
  this.params_;
  
  /**
   * @private
   * @type {org.apache.royale.html.beads.layouts.HorizontalLayout}
   */
  this.$ID_10_8;
  
  /**
   * @private
   * @type {org.apache.royale.html.beads.models.ListPresentationModel}
   */
  this.$ID_10_9;
  
  /**
   * @private
   * @type {org.apache.royale.html.Label}
   */
  this.$ID_10_10;
  
  /**
   * @private
   * @type {org.apache.royale.html.Label}
   */
  this.label_;
  
  /**
   * @private
   * @type {org.apache.royale.html.elements.A}
   */
  this.link_;
  
  /**
   * @private
   * @type {org.apache.royale.html.DataContainer}
   */
  this.attributes_;
  
  /**
   * @private
   * @type {org.apache.royale.html.beads.models.ListPresentationModel}
   */
  this.$ID_10_11;
  
  /**
   * @private
   * @type {org.apache.royale.html.MultilineLabel}
   */
  this.description_;
  
  /**
   * @private
   * @type {Array}
   */
  this.mxmldd;
  
  /**
   * @private
   * @type {Array}
   */
  this.mxmldp;

  this.generateMXMLAttributes([
    3,
    'className',
    true,
    'property',
    'percentWidth',
    true,
    100.0,
    'beads',
    null,
    [
      org.apache.royale.html.beads.layouts.VerticalFlexLayout,
      1,
      '_id',
      true,
      '$ID_10_0',
      0,
      0,
      null,
      org.apache.royale.binding.ItemRendererDataBinding,
      1,
      '_id',
      true,
      '$ID_10_1',
      0,
      0,
      null
    ],
    0,
    0
  ]);
  
};
goog.inherits(MethodDetailRenderer, org.apache.royale.html.supportClasses.MXMLItemRenderer);




/**
 * @private
 * @type {Object}
 */
MethodDetailRenderer.fakeBothPlatforms = {"addEventListener":1, "removeEventListener":1, "hasEventListener":1, "dispatchEvent":1, "toString":1};


;


;





MethodDetailRenderer.prototype.set__data = function(value) {
  MethodDetailRenderer.superClass_.set__data.apply(this, [value]);
  if (value["returnhref"])
    this.propertyTypeGroup.removeElement(this.label);
  else
    this.propertyTypeGroup.removeElement(this.link);
  this.target.element.id = this.obj.qname;
  if (this.obj.platforms.length == 1 && !MethodDetailRenderer.fakeBothPlatforms[this.obj.qname]) {
    if (this.obj.platforms[0] == "swf")
      this.target.className += " swfonly";
    if (this.obj.platforms[0] == "js")
      this.target.className += " jsonly";
  }
};


/**
 * @nocollapse
 * @export
 * @type {ASDocClassMembers}
 */
MethodDetailRenderer.prototype.obj;


MethodDetailRenderer.prototype.get__obj = function() {
  return this.data;
};


Object.defineProperties(MethodDetailRenderer.prototype, /** @lends {MethodDetailRenderer.prototype} */ {
/**
 * @type {Object}
 */
data: {
get: org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.get__data,
set: MethodDetailRenderer.prototype.set__data},
/**
 * @type {ASDocClassMembers}
 */
obj: {
get: MethodDetailRenderer.prototype.get__obj}}
);Object.defineProperties(MethodDetailRenderer.prototype, /** @lends {MethodDetailRenderer.prototype} */ {
  target: {
    /** @this {MethodDetailRenderer} */
    get: function() {
      return this.target_;
    },
    /** @this {MethodDetailRenderer} */
    set: function(value) {
      if (value != this.target_) {
        this.target_ = value;
        this.dispatchEvent(org.apache.royale.events.ValueChangeEvent.createUpdateEvent(this, 'target', null, value));
      }
    }
  },
  propertyTypeGroup: {
    /** @this {MethodDetailRenderer} */
    get: function() {
      return this.propertyTypeGroup_;
    },
    /** @this {MethodDetailRenderer} */
    set: function(value) {
      if (value != this.propertyTypeGroup_) {
        this.propertyTypeGroup_ = value;
        this.dispatchEvent(org.apache.royale.events.ValueChangeEvent.createUpdateEvent(this, 'propertyTypeGroup', null, value));
      }
    }
  },
  params: {
    /** @this {MethodDetailRenderer} */
    get: function() {
      return this.params_;
    },
    /** @this {MethodDetailRenderer} */
    set: function(value) {
      if (value != this.params_) {
        this.params_ = value;
        this.dispatchEvent(org.apache.royale.events.ValueChangeEvent.createUpdateEvent(this, 'params', null, value));
      }
    }
  },
  label: {
    /** @this {MethodDetailRenderer} */
    get: function() {
      return this.label_;
    },
    /** @this {MethodDetailRenderer} */
    set: function(value) {
      if (value != this.label_) {
        this.label_ = value;
        this.dispatchEvent(org.apache.royale.events.ValueChangeEvent.createUpdateEvent(this, 'label', null, value));
      }
    }
  },
  link: {
    /** @this {MethodDetailRenderer} */
    get: function() {
      return this.link_;
    },
    /** @this {MethodDetailRenderer} */
    set: function(value) {
      if (value != this.link_) {
        this.link_ = value;
        this.dispatchEvent(org.apache.royale.events.ValueChangeEvent.createUpdateEvent(this, 'link', null, value));
      }
    }
  },
  attributes: {
    /** @this {MethodDetailRenderer} */
    get: function() {
      return this.attributes_;
    },
    /** @this {MethodDetailRenderer} */
    set: function(value) {
      if (value != this.attributes_) {
        this.attributes_ = value;
        this.dispatchEvent(org.apache.royale.events.ValueChangeEvent.createUpdateEvent(this, 'attributes', null, value));
      }
    }
  },
  description: {
    /** @this {MethodDetailRenderer} */
    get: function() {
      return this.description_;
    },
    /** @this {MethodDetailRenderer} */
    set: function(value) {
      if (value != this.description_) {
        this.description_ = value;
        this.dispatchEvent(org.apache.royale.events.ValueChangeEvent.createUpdateEvent(this, 'description', null, value));
      }
    }
  },
  'MXMLDescriptor': {
    /** @this {MethodDetailRenderer} */
    get: function() {
      if (this.mxmldd == undefined)
      {
        /** @type {Array} */
        var arr = MethodDetailRenderer.superClass_.get__MXMLDescriptor.apply(this);
        /** @type {Array} */
        var mxmldd = [
          org.apache.royale.html.Group,
          2,
          '_id',
          true,
          '$ID_10_4',
          'beads',
          null,
          [
            org.apache.royale.html.beads.layouts.HorizontalLayout,
            1,
            '_id',
            true,
            '$ID_10_2',
            0,
            0,
            null
          ],
          0,
          0,
          [
            org.apache.royale.html.Label,
            2,
            'id',
            true,
            'target',
            'className',
            true,
            'propertyQNameTitle',
            0,
            0,
            null,
            org.apache.royale.html.Label,
            2,
            '_id',
            true,
            '$ID_10_3',
            'text',
            true,
            'method',
            0,
            0,
            null
          ],
          org.apache.royale.html.Group,
          3,
          'id',
          true,
          'propertyTypeGroup',
          'className',
          true,
          'propertyTypeGroup',
          'beads',
          null,
          [
            org.apache.royale.html.beads.layouts.HorizontalLayout,
            1,
            '_id',
            true,
            '$ID_10_5',
            0,
            0,
            null
          ],
          0,
          0,
          [
            org.apache.royale.html.Label,
            2,
            '_id',
            true,
            '$ID_10_6',
            'className',
            true,
            'propertyQName',
            0,
            0,
            null,
            org.apache.royale.html.Label,
            2,
            '_id',
            true,
            '$ID_10_7',
            'text',
            true,
            '(',
            0,
            0,
            null,
            org.apache.royale.html.DataContainer,
            5,
            'id',
            true,
            'params',
            'className',
            true,
            'signatureParamsList',
            'style',
            true,
            'border-style:none',
            'itemRenderer',
            true,
            new org.apache.royale.core.ClassFactory(ParameterRenderer),
            'beads',
            null,
            [
              org.apache.royale.html.beads.layouts.HorizontalLayout,
              1,
              '_id',
              true,
              '$ID_10_8',
              0,
              0,
              null,
              org.apache.royale.html.beads.models.ListPresentationModel,
              2,
              '_id',
              true,
              '$ID_10_9',
              'rowHeight',
              true,
              NaN,
              0,
              0,
              null
            ],
            0,
            0,
            null,
            org.apache.royale.html.Label,
            2,
            '_id',
            true,
            '$ID_10_10',
            'text',
            true,
            '):',
            0,
            0,
            null,
            org.apache.royale.html.Label,
            2,
            'id',
            true,
            'label',
            'className',
            true,
            'propertyType',
            0,
            0,
            null,
            org.apache.royale.html.elements.A,
            2,
            'id',
            true,
            'link',
            'className',
            true,
            'propertyTypeLink',
            0,
            0,
            null
          ],
          org.apache.royale.html.DataContainer,
          5,
          'id',
          true,
          'attributes',
          'className',
          true,
          'attributeList',
          'itemRenderer',
          true,
          new org.apache.royale.core.ClassFactory(AttributeRenderer),
          'percentWidth',
          true,
          100.0,
          'beads',
          null,
          [
            org.apache.royale.html.beads.models.ListPresentationModel,
            2,
            '_id',
            true,
            '$ID_10_11',
            'rowHeight',
            true,
            NaN,
            0,
            0,
            null
          ],
          0,
          0,
          null,
          org.apache.royale.html.MultilineLabel,
          2,
          'id',
          true,
          'description',
          'percentWidth',
          true,
          100.0,
          0,
          0,
          null
        ];
        if (arr)
          this.mxmldd = arr.concat(mxmldd);
        else
          this.mxmldd = mxmldd;
      }
      return this.mxmldd;
    }
  }
});
/**
 * @export
 */
MethodDetailRenderer.prototype._bindings = [
8,
["obj", "qname"],
null,
["target", "text"],
["data", "qname"],
null,
["$ID_10_6", "text"],
["data", "params"],
null,
["params", "dataProvider"],
["data", "return"],
null,
["label", "text"],
["data", "return"],
null,
["link", "text"],
["data", "returnhref"],
null,
["link", "href"],
["data", "attributes"],
null,
["attributes", "dataProvider"],
/** @this {MethodDetailRenderer} */
function() { return org.apache.royale.utils.string.sanitizeHtml(this.obj.description); },
null,
["description", "html"],
0,
2,
"obj",
"dataChange",
[0,7],
null,
[
1,
2,
"qname",
"__NoChangeEvent__",
0,
null,
null,
2,
2,
"description",
"__NoChangeEvent__",
7,
null,
null,
null],
3,
2,
"data",
["dataChange","__NoChangeEvent__"],
[1,2,3,4,5,6],
null,
[
4,
2,
"qname",
"__NoChangeEvent__",
1,
null,
null,
5,
2,
"params",
"__NoChangeEvent__",
2,
null,
null,
6,
2,
"return",
"__NoChangeEvent__",
[3,4],
null,
null,
7,
2,
"returnhref",
"__NoChangeEvent__",
5,
null,
null,
8,
2,
"attributes",
"__NoChangeEvent__",
6,
null,
null,
null]];
/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
MethodDetailRenderer.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'MethodDetailRenderer', qName: 'MethodDetailRenderer', kind: 'class'  }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
MethodDetailRenderer.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    accessors: function () {
      return {
        'data': { type: 'Object', access: 'writeonly', declaredBy: 'MethodDetailRenderer'},
        'obj': { type: 'ASDocClassMembers', access: 'readonly', declaredBy: 'MethodDetailRenderer'},
        'target': { type: 'org.apache.royale.html.Label', access: 'readwrite', declaredBy: 'MethodDetailRenderer'},
        'propertyTypeGroup': { type: 'org.apache.royale.html.Group', access: 'readwrite', declaredBy: 'MethodDetailRenderer'},
        'params': { type: 'org.apache.royale.html.DataContainer', access: 'readwrite', declaredBy: 'MethodDetailRenderer'},
        'label': { type: 'org.apache.royale.html.Label', access: 'readwrite', declaredBy: 'MethodDetailRenderer'},
        'link': { type: 'org.apache.royale.html.elements.A', access: 'readwrite', declaredBy: 'MethodDetailRenderer'},
        'attributes': { type: 'org.apache.royale.html.DataContainer', access: 'readwrite', declaredBy: 'MethodDetailRenderer'},
        'description': { type: 'org.apache.royale.html.MultilineLabel', access: 'readwrite', declaredBy: 'MethodDetailRenderer'}
      };
    },
    methods: function () {
      return {
        'MethodDetailRenderer': { type: '', declaredBy: 'MethodDetailRenderer'}
      };
    }
  };
};
/**
 * @const
 * @type {number}
 */
MethodDetailRenderer.prototype.ROYALE_COMPILE_FLAGS = 9;
/**
 * Provide reflection support for distinguishing dynamic fields on class object (static)
 * @const
 * @type {Array<string>}
 */
MethodDetailRenderer.prototype.ROYALE_INITIAL_STATICS = Object.keys(MethodDetailRenderer);
