/**
 * Generated by Apache Royale Compiler from OptionalHashAnchorStringItemRenderer.as
 * OptionalHashAnchorStringItemRenderer
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('OptionalHashAnchorStringItemRenderer');
/* Royale Dependency List: org.apache.royale.core.IItemRendererOwnerView,org.apache.royale.html.List,org.apache.royale.utils.Language*/

goog.require('org.apache.royale.html.supportClasses.StringItemRenderer');
goog.require('org.apache.royale.core.IOwnerViewItemRenderer');



/**
 *  constructor.
 *
 *  @langversion 3.0
 *  @playerversion Flash 10.2
 *  @playerversion AIR 2.6
 *  @productversion Royale 0.0
 * @constructor
 * @extends {org.apache.royale.html.supportClasses.StringItemRenderer}
 * @implements {org.apache.royale.core.IOwnerViewItemRenderer}
 */
OptionalHashAnchorStringItemRenderer = function() {
  OptionalHashAnchorStringItemRenderer.base(this, 'constructor');
  this.typeNames += " OptionalHashAnchorStringItemRenderer";
};
goog.inherits(OptionalHashAnchorStringItemRenderer, org.apache.royale.html.supportClasses.StringItemRenderer);


/**
 * @private
 * @type {org.apache.royale.core.IItemRendererOwnerView}
 */
OptionalHashAnchorStringItemRenderer.prototype.OptionalHashAnchorStringItemRenderer__itemRendererOwnerView = null;


OptionalHashAnchorStringItemRenderer.prototype.set__text = function(value) {
  var /** @type {boolean} */ last = false;
  if (org.apache.royale.utils.Language.is(this.parent, org.apache.royale.html.List)) {
    var /** @type {number} */ n = (this.parent.dataProvider["length"]) >> 0;
    last = n == this.index + 1;
  }
  
  var /** @type {string} */ href = org.apache.royale.utils.Language.string(this.data["href"]);
  if (!href)
    this.element.innerHTML = value + (last ? "" : " -> ");
  else
    this.element.innerHTML = "<a href='#!" + href + "' class='HashAnchorAnchor'>" + value + "</a>" + (last ? "" : " -> ");
};


/**
 * @nocollapse
 * @export
 * @type {org.apache.royale.core.IItemRendererOwnerView}
 */
OptionalHashAnchorStringItemRenderer.prototype.itemRendererOwnerView;


OptionalHashAnchorStringItemRenderer.prototype.get__itemRendererOwnerView = function() {
  return this.OptionalHashAnchorStringItemRenderer__itemRendererOwnerView;
};


OptionalHashAnchorStringItemRenderer.prototype.set__itemRendererOwnerView = function(value) {
  this.OptionalHashAnchorStringItemRenderer__itemRendererOwnerView = value;
};


Object.defineProperties(OptionalHashAnchorStringItemRenderer.prototype, /** @lends {OptionalHashAnchorStringItemRenderer.prototype} */ {
/**
 * @type {string}
 */
text: {
get: org.apache.royale.html.supportClasses.StringItemRenderer.prototype.get__text,
set: OptionalHashAnchorStringItemRenderer.prototype.set__text},
/**
 * @type {org.apache.royale.core.IItemRendererOwnerView}
 */
itemRendererOwnerView: {
get: OptionalHashAnchorStringItemRenderer.prototype.get__itemRendererOwnerView,
set: OptionalHashAnchorStringItemRenderer.prototype.set__itemRendererOwnerView}}
);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
OptionalHashAnchorStringItemRenderer.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'OptionalHashAnchorStringItemRenderer', qName: 'OptionalHashAnchorStringItemRenderer', kind: 'class' }], interfaces: [org.apache.royale.core.IOwnerViewItemRenderer] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
OptionalHashAnchorStringItemRenderer.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    accessors: function () {
      return {
        'text': { type: 'String', access: 'writeonly', declaredBy: 'OptionalHashAnchorStringItemRenderer'},
        'itemRendererOwnerView': { type: 'org.apache.royale.core.IItemRendererOwnerView', access: 'readwrite', declaredBy: 'OptionalHashAnchorStringItemRenderer'}
      };
    },
    methods: function () {
      return {
        'OptionalHashAnchorStringItemRenderer': { type: '', declaredBy: 'OptionalHashAnchorStringItemRenderer'}
      };
    }
  };
};
/**
 * @const
 * @type {number}
 */
OptionalHashAnchorStringItemRenderer.prototype.ROYALE_COMPILE_FLAGS = 9;
