/**
 * Generated by Apache Royale Compiler from org/apache/royale/states/ItemAndDescriptor.as
 * org.apache.royale.states.ItemAndDescriptor
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('org.apache.royale.states.ItemAndDescriptor');
/* Royale Dependency List: */



/**
 *  Constructor.
 *  
 *  @langversion 3.0
 *  @playerversion Flash 9
 *  @playerversion AIR 1.1
 *  @productversion Royale 1.0.0
 * @constructor
 */
org.apache.royale.states.ItemAndDescriptor = function() {
  ;
};


/**
 * @private
 * @type {Object}
 */
org.apache.royale.states.ItemAndDescriptor.prototype.org_apache_royale_states_ItemAndDescriptor__items;


/**
 * @private
 * @type {Array}
 */
org.apache.royale.states.ItemAndDescriptor.prototype.org_apache_royale_states_ItemAndDescriptor__descriptor;


/**
 * @nocollapse
 * @export
 * @type {Object}
 */
org.apache.royale.states.ItemAndDescriptor.prototype.items;


org.apache.royale.states.ItemAndDescriptor.prototype.get__items = function() {
  return this.org_apache_royale_states_ItemAndDescriptor__items;
};


org.apache.royale.states.ItemAndDescriptor.prototype.set__items = function(value) {
  this.org_apache_royale_states_ItemAndDescriptor__items = value;
};


/**
 * @nocollapse
 * @export
 * @type {Array}
 */
org.apache.royale.states.ItemAndDescriptor.prototype.descriptor;


org.apache.royale.states.ItemAndDescriptor.prototype.get__descriptor = function() {
  return this.org_apache_royale_states_ItemAndDescriptor__descriptor;
};


org.apache.royale.states.ItemAndDescriptor.prototype.set__descriptor = function(value) {
  this.org_apache_royale_states_ItemAndDescriptor__descriptor = value;
};


Object.defineProperties(org.apache.royale.states.ItemAndDescriptor.prototype, /** @lends {org.apache.royale.states.ItemAndDescriptor.prototype} */ {
/**
 * @type {Object}
 */
items: {
get: org.apache.royale.states.ItemAndDescriptor.prototype.get__items,
set: org.apache.royale.states.ItemAndDescriptor.prototype.set__items},
/**
 * @type {Array}
 */
descriptor: {
get: org.apache.royale.states.ItemAndDescriptor.prototype.get__descriptor,
set: org.apache.royale.states.ItemAndDescriptor.prototype.set__descriptor}}
);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.states.ItemAndDescriptor.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'ItemAndDescriptor', qName: 'org.apache.royale.states.ItemAndDescriptor', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.states.ItemAndDescriptor.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    accessors: function () {
      return {
        'items': { type: 'Object', access: 'readwrite', declaredBy: 'org.apache.royale.states.ItemAndDescriptor'},
        'descriptor': { type: 'Array', access: 'readwrite', declaredBy: 'org.apache.royale.states.ItemAndDescriptor'}
      };
    },
    methods: function () {
      return {
        'ItemAndDescriptor': { type: '', declaredBy: 'org.apache.royale.states.ItemAndDescriptor'}
      };
    }
  };
};
/**
 * @const
 * @type {number}
 */
org.apache.royale.states.ItemAndDescriptor.prototype.ROYALE_COMPILE_FLAGS = 10;

//# sourceMappingURL=./ItemAndDescriptor.js.map
