/**
 * Generated by Apache Royale Compiler from org/apache/royale/events/ElementEvents.as
 * org.apache.royale.events.ElementEvents
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('org.apache.royale.events.ElementEvents');
/* Royale Dependency List: */



/**
 * @constructor
 */
org.apache.royale.events.ElementEvents = function() {
};


/**
 * @nocollapse
 * @const
 * @type {Object}
 */
org.apache.royale.events.ElementEvents.elementEvents = {'click':1, 'dblclick':1, 'change':1, 'keyup':1, 'keydown':1, 'load':1, 'mouseenter':1, 'mouseleave':1, 'mouseover':1, 'mouseout':1, 'mouseup':1, 'mousedown':1, 'mousemove':1, 'rollover':1, 'rollout':1, 'wheel':1};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.events.ElementEvents.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'ElementEvents', qName: 'org.apache.royale.events.ElementEvents', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.events.ElementEvents.prototype.ROYALE_REFLECTION_INFO = function () {
  return {};
};
/**
 * @const
 * @type {number}
 */
org.apache.royale.events.ElementEvents.prototype.ROYALE_COMPILE_FLAGS = 10;

//# sourceMappingURL=./ElementEvents.js.map
