/**
 * Generated by Apache Royale Compiler from org/apache/royale/events/Event.as
 * org.apache.royale.events.Event
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('org.apache.royale.events.Event');
/* Royale Dependency List: org.apache.royale.core.IRoyaleElement,org.apache.royale.events.IEventDispatcher,org.apache.royale.utils.Language*/

goog.require('org.apache.royale.events.IRoyaleEvent');



/**
 * @constructor
 * @extends {goog.events.Event}
 * @implements {org.apache.royale.events.IRoyaleEvent}
 * @param {string} type
 * @param {boolean=} bubbles
 * @param {boolean=} cancelable
 */
org.apache.royale.events.Event = function(type, bubbles, cancelable) {
  bubbles = typeof bubbles !== 'undefined' ? bubbles : false;
  cancelable = typeof cancelable !== 'undefined' ? cancelable : false;
  org.apache.royale.events.Event.base(this, 'constructor', type);
  this.bubbles = bubbles;
  this.cancelable = cancelable;
};
goog.inherits(org.apache.royale.events.Event, goog.events.Event);


/**
 * @nocollapse
 * @const
 * @type {string}
 */
org.apache.royale.events.Event.CHANGE = "change";


/**
 * @nocollapse
 * @const
 * @type {string}
 */
org.apache.royale.events.Event.COMPLETE = "complete";


/**
 * @nocollapse
 * @const
 * @type {string}
 */
org.apache.royale.events.Event.SELECT = "select";


/**
 * @nocollapse
 * @const
 * @type {string}
 */
org.apache.royale.events.Event.OPEN = "open";


/**
 * @nocollapse
 * @const
 * @type {string}
 */
org.apache.royale.events.Event.DEACTIVATE = "deactivate";


/**
 * @nocollapse
 * @const
 * @type {string}
 */
org.apache.royale.events.Event.ADDED = "added";


/**
 * @nocollapse
 * @const
 * @type {string}
 */
org.apache.royale.events.Event.REMOVED = "removed";


/**
 * @nocollapse
 * @const
 * @type {string}
 */
org.apache.royale.events.Event.CLOSE = "close";


/**
 * @nocollapse
 * @const
 * @type {string}
 */
org.apache.royale.events.Event.CANCEL = "cancel";


/**
 * @nocollapse
 * @const
 * @type {string}
 */
org.apache.royale.events.Event.CONNECT = "connect";


/**
 * @nocollapse
 * @const
 * @type {string}
 */
org.apache.royale.events.Event.REMOVED_FROM_STAGE = "removedFromStage";


/**
 * @nocollapse
 * @const
 * @type {string}
 */
org.apache.royale.events.Event.ADDED_TO_STAGE = "addedToStage";


/**
 * @nocollapse
 * @const
 * @type {string}
 */
org.apache.royale.events.Event.MOUSE_LEAVE = "mouseLeave";


/**
 * @nocollapse
 * @const
 * @type {string}
 */
org.apache.royale.events.Event.ENTER_FRAME = "enterFrame";


/**
 * @nocollapse
 * @const
 * @type {string}
 */
org.apache.royale.events.Event.RESIZE = "resize";


/**
 * @type {boolean}
 */
org.apache.royale.events.Event.prototype.bubbles;


/**
 * @type {boolean}
 */
org.apache.royale.events.Event.prototype.cancelable;


/**
 * @private
 * @type {boolean}
 */
org.apache.royale.events.Event.prototype.org_apache_royale_events_Event__immediatePropogationStopped;


/**
 */
org.apache.royale.events.Event.prototype.stopImmediatePropagation = function() {
  this.org_apache_royale_events_Event__immediatePropogationStopped = true;
};


/**
 * @return {org.apache.royale.events.IRoyaleEvent}
 */
org.apache.royale.events.Event.prototype.cloneEvent = function() {
  return new org.apache.royale.events.Event(this.type, this.bubbles, this.cancelable);
};


/**
 * @return {boolean}
 */
org.apache.royale.events.Event.prototype.isDefaultPrevented = function() {
  return this.defaultPrevented;
};


/**
 * Determine if the target is the same as the event's target.  The event's target
 * can sometimes be an internal target so this tests if the outer component
 * matches the potential target
 *
 * @langversion 3.0
 * @playerversion Flash 10.2
 * @playerversion AIR 2.6
 * @productversion Royale 0.0
 * @royaleignorecoercion Object
 * @param {org.apache.royale.events.IEventDispatcher} potentialTarget
 * @return {boolean}
 */
org.apache.royale.events.Event.prototype.isSameTarget = function(potentialTarget) {
  if (potentialTarget === this.target)
    return true;
  if (org.apache.royale.utils.Language.is(this.target, org.apache.royale.core.IRoyaleElement) && this.target.royale_wrapper === potentialTarget)
    return true;
  return false;
};


/**
 * @param {string} className
 * @param {...} args
 * @return {string}
 */
org.apache.royale.events.Event.prototype.formatToString = function(className, args) {
  args = Array.prototype.slice.call(arguments, 1);
  var foreachiter0_target = args;
  for (var foreachiter0 in foreachiter0_target) 
  {
  var s = foreachiter0_target[foreachiter0];
  
    className += " " + s;}
  
  return className;
};


/**
 * @nocollapse
 * @export
 * @type {boolean}
 */
org.apache.royale.events.Event.prototype.immediatePropogationStopped;


org.apache.royale.events.Event.prototype.get__immediatePropogationStopped = function() {
  return this.org_apache_royale_events_Event__immediatePropogationStopped;
};


/**
 * @nocollapse
 * @export
 * @type {number}
 */
org.apache.royale.events.Event.prototype.eventPhase;


org.apache.royale.events.Event.prototype.get__eventPhase = function() {
  return 0;
};


Object.defineProperties(org.apache.royale.events.Event.prototype, /** @lends {org.apache.royale.events.Event.prototype} */ {
/**
 * @type {boolean}
 */
immediatePropogationStopped: {
get: org.apache.royale.events.Event.prototype.get__immediatePropogationStopped},
/**
 * @type {number}
 */
eventPhase: {
get: org.apache.royale.events.Event.prototype.get__eventPhase}}
);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.events.Event.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'Event', qName: 'org.apache.royale.events.Event', kind: 'class' }], interfaces: [org.apache.royale.events.IRoyaleEvent] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.events.Event.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {
      return {
        'bubbles': { type: 'Boolean', get_set: function (/** org.apache.royale.events.Event */ inst, /** * */ v) {return v !== undefined ? inst.bubbles = v : inst.bubbles;}},
        'cancelable': { type: 'Boolean', get_set: function (/** org.apache.royale.events.Event */ inst, /** * */ v) {return v !== undefined ? inst.cancelable = v : inst.cancelable;}}
      };
    },
    accessors: function () {
      return {
        'immediatePropogationStopped': { type: 'Boolean', access: 'readonly', declaredBy: 'org.apache.royale.events.Event'},
        'eventPhase': { type: 'uint', access: 'readonly', declaredBy: 'org.apache.royale.events.Event'}
      };
    },
    methods: function () {
      return {
        'Event': { type: '', declaredBy: 'org.apache.royale.events.Event', parameters: function () { return [ 'String', false ,'Boolean', true ,'Boolean', true ]; }},
        'stopImmediatePropagation': { type: 'void', declaredBy: 'org.apache.royale.events.Event'},
        'cloneEvent': { type: 'org.apache.royale.events.IRoyaleEvent', declaredBy: 'org.apache.royale.events.Event'},
        'isDefaultPrevented': { type: 'Boolean', declaredBy: 'org.apache.royale.events.Event'},
        'isSameTarget': { type: 'Boolean', declaredBy: 'org.apache.royale.events.Event', parameters: function () { return [ 'org.apache.royale.events.IEventDispatcher', false ]; }},
        'formatToString': { type: 'String', declaredBy: 'org.apache.royale.events.Event', parameters: function () { return [ 'String', false ,'Array', false ]; }}
      };
    }
  };
};
/**
 * @const
 * @type {number}
 */
org.apache.royale.events.Event.prototype.ROYALE_COMPILE_FLAGS = 10;

//# sourceMappingURL=./Event.js.map
