/**
 * Generated by Apache Royale Compiler from org\apache\royale\utils\CSSContainerUtils.as
 * org.apache.royale.utils.CSSContainerUtils
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('org.apache.royale.utils.CSSContainerUtils');

goog.require('org.apache.royale.core.ValuesManager');
goog.require('org.apache.royale.geom.Rectangle');
goog.require('org.apache.royale.utils.CSSUtils');
goog.require('org.apache.royale.utils.Language');



/**
 * @constructor
 */
org.apache.royale.utils.CSSContainerUtils = function() {
};


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('org.apache.royale.utils.CSSContainerUtils', org.apache.royale.utils.CSSContainerUtils);


/**
 *  Compute the width/thickness of the four border edges.
 *  
 *  @asparam object The object with style values.
 *  @asparam quick True to assume all four edges have the same widths.
 *  @asreturn A Rectangle representing the four sides.
 * 
 *  @langversion 3.0
 *  @playerversion Flash 10.2
 *  @playerversion AIR 2.6
 *  @productversion Royale 0.0
 * @export
 * @param {Object} object
 * @param {boolean=} quick
 * @return {org.apache.royale.geom.Rectangle}
 */
org.apache.royale.utils.CSSContainerUtils.getBorderMetrics = function(object, quick) {
  quick = typeof quick !== 'undefined' ? quick : false;
  var /** @type {Object} */ borderThickness = org.apache.royale.core.ValuesManager["valuesImpl"].getValue(object, "border-width");
  var /** @type {Object} */ borderStyle = org.apache.royale.core.ValuesManager["valuesImpl"].getValue(object, "border-style");
  var /** @type {Object} */ border = org.apache.royale.core.ValuesManager["valuesImpl"].getValue(object, "border");
  var /** @type {number} */ borderOffset;
  if (borderStyle == "none")
    borderOffset = 0; else if (borderStyle != null && borderThickness != null) {
    if (org.apache.royale.utils.Language.is(borderThickness, String))
      borderOffset = org.apache.royale.utils.CSSUtils.toNumber(org.apache.royale.utils.Language.as(borderThickness, String), object.width);
    else
      borderOffset = Number(borderThickness);
    if (isNaN(borderOffset))
      borderOffset = 0;
  } else {
    border = org.apache.royale.core.ValuesManager["valuesImpl"].getValue(object, "border");
    if (border != null) {
      if (org.apache.royale.utils.Language.is(border, Array)) {
        borderOffset = org.apache.royale.utils.CSSUtils.toNumber(String(border[0]), object.width);
        borderStyle = border[1];
      }
      else if (border == "none")
        borderOffset = 0;
      else if (org.apache.royale.utils.Language.is(border, String))
        borderOffset = org.apache.royale.utils.CSSUtils.toNumber(org.apache.royale.utils.Language.as(border, String), object.width);
      else
        borderOffset = Number(border);
    }
    else
      borderOffset = 0;
  }
  if (quick)
    return new org.apache.royale.geom.Rectangle(borderOffset, borderOffset, 0, 0);
  var /** @type {number} */ widthTop = borderOffset;
  var /** @type {number} */ widthLeft = borderOffset;
  var /** @type {number} */ widthBottom = borderOffset;
  var /** @type {number} */ widthRight = borderOffset;
  var /** @type {*} */ value;
  var /** @type {Array} */ values;
  var /** @type {number} */ n = 0;
  value = org.apache.royale.core.ValuesManager["valuesImpl"].getValue(object, "border-top");
  if (value != null) {
    if (org.apache.royale.utils.Language.is(value, Array))
      values = org.apache.royale.utils.Language.as(value, Array);
    else
      values = value.split(" ");
    n = values.length;
    widthTop = org.apache.royale.utils.CSSUtils.toNumber(values[0]);
  }
  value = org.apache.royale.core.ValuesManager["valuesImpl"].getValue(object, "border-left");
  if (value != null) {
    if (org.apache.royale.utils.Language.is(value, Array))
      values = org.apache.royale.utils.Language.as(value, Array);
    else
      values = value.split(" ");
    n = values.length;
    widthLeft = org.apache.royale.utils.CSSUtils.toNumber(values[0]);
  }
  value = org.apache.royale.core.ValuesManager["valuesImpl"].getValue(object, "border-bottom");
  if (value != null) {
    if (org.apache.royale.utils.Language.is(value, Array))
      values = org.apache.royale.utils.Language.as(value, Array);
    else
      values = value.split(" ");
    n = values.length;
    widthBottom = org.apache.royale.utils.CSSUtils.toNumber(values[0]);
  }
  value = org.apache.royale.core.ValuesManager["valuesImpl"].getValue(object, "border-right");
  if (value != null) {
    if (org.apache.royale.utils.Language.is(value, Array))
      values = org.apache.royale.utils.Language.as(value, Array);
    else
      values = value.split(" ");
    n = values.length;
    widthRight = org.apache.royale.utils.CSSUtils.toNumber(values[0]);
  }
  return new org.apache.royale.geom.Rectangle(widthLeft, widthTop, widthRight - widthLeft, widthTop - widthBottom);
};


/**
 *  Compute the width/thickness of the four padding sides.
 *  
 *  @asparam object The object with style values.
 *  @asreturn A Rectangle representing the padding on each of the four sides.
 * 
 *  @langversion 3.0
 *  @playerversion Flash 10.2
 *  @playerversion AIR 2.6
 *  @productversion Royale 0.0
 * @export
 * @param {Object} object
 * @return {org.apache.royale.geom.Rectangle}
 */
org.apache.royale.utils.CSSContainerUtils.getPaddingMetrics = function(object) {
  var /** @type {Object} */ paddingLeft;
  var /** @type {Object} */ paddingTop;
  var /** @type {Object} */ paddingRight;
  var /** @type {Object} */ paddingBottom;
  var /** @type {Object} */ padding = org.apache.royale.core.ValuesManager["valuesImpl"].getValue(object, "padding");
  paddingLeft = org.apache.royale.core.ValuesManager["valuesImpl"].getValue(object, "padding-left");
  paddingTop = org.apache.royale.core.ValuesManager["valuesImpl"].getValue(object, "padding-top");
  paddingRight = org.apache.royale.core.ValuesManager["valuesImpl"].getValue(object, "padding-right");
  paddingBottom = org.apache.royale.core.ValuesManager["valuesImpl"].getValue(object, "padding-bottom");
  var /** @type {number} */ pl = org.apache.royale.utils.CSSUtils.getLeftValue(paddingLeft, padding, object.width);
  var /** @type {number} */ pt = org.apache.royale.utils.CSSUtils.getTopValue(paddingTop, padding, object.height);
  var /** @type {number} */ pr = org.apache.royale.utils.CSSUtils.getRightValue(paddingRight, padding, object.width);
  var /** @type {number} */ pb = org.apache.royale.utils.CSSUtils.getBottomValue(paddingBottom, padding, object.height);
  return new org.apache.royale.geom.Rectangle(pl, pt, pr - pl, pb - pt);
};


/**
 *  Combine padding and border.  Often used in non-containers.
 *  
 *  @asparam object The object with style values.
 *  @asreturn A Rectangle representing the padding and border on each of the four sides.
 * 
 *  @langversion 3.0
 *  @playerversion Flash 10.2
 *  @playerversion AIR 2.6
 *  @productversion Royale 0.0
 * @export
 * @param {Object} object
 * @return {org.apache.royale.geom.Rectangle}
 */
org.apache.royale.utils.CSSContainerUtils.getBorderAndPaddingMetrics = function(object) {
  var /** @type {org.apache.royale.geom.Rectangle} */ borderMetrics = org.apache.royale.utils.CSSContainerUtils.getBorderMetrics(object);
  var /** @type {org.apache.royale.geom.Rectangle} */ paddingMetrics = org.apache.royale.utils.CSSContainerUtils.getPaddingMetrics(object);
  return new org.apache.royale.geom.Rectangle(borderMetrics.left + paddingMetrics.left, borderMetrics.top + paddingMetrics.top, borderMetrics.width + paddingMetrics.width, borderMetrics.height + paddingMetrics.height);
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.utils.CSSContainerUtils.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'CSSContainerUtils', qName: 'org.apache.royale.utils.CSSContainerUtils', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.utils.CSSContainerUtils.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {return {};},
    methods: function () {
      return {
        '|getBorderMetrics': { type: 'org.apache.royale.geom.Rectangle', declaredBy: 'org.apache.royale.utils.CSSContainerUtils', parameters: function () { return [  { index: 1, type: 'Object', optional: false },{ index: 2, type: 'Boolean', optional: true } ]; }},
        '|getPaddingMetrics': { type: 'org.apache.royale.geom.Rectangle', declaredBy: 'org.apache.royale.utils.CSSContainerUtils', parameters: function () { return [  { index: 1, type: 'Object', optional: false } ]; }},
        '|getBorderAndPaddingMetrics': { type: 'org.apache.royale.geom.Rectangle', declaredBy: 'org.apache.royale.utils.CSSContainerUtils', parameters: function () { return [  { index: 1, type: 'Object', optional: false } ]; }}
      };
    }
  };
};