/**
 * Generated by Apache Royale Compiler from org/apache/royale/utils/sendStrandEvent.as
 * org.apache.royale.utils.sendStrandEvent
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('org.apache.royale.utils.sendStrandEvent');
/* Royale Dependency List: org.apache.royale.core.IStrand,org.apache.royale.events.IEventDispatcher*/




/**
 * Helper function for dispatching events from the strand
 * Using this function prevent the need to cast IStrand objects
 * It also allows better minification
 * @royalesuppressexport
 * @royaleignorecoercion org.apache.royale.events.IEventDispatcher
 * @param {org.apache.royale.core.IStrand} strand
 * @param {Object} event
 * @return {boolean}
 */
org.apache.royale.utils.sendStrandEvent = function(strand, event) {
  
  return strand.dispatchEvent(event);
}
