/**
 * Generated by Apache Royale Compiler from org\apache\royale\html\supportClasses\IDataGridColumn.as
 * org.apache.royale.html.supportClasses.IDataGridColumn
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('org.apache.royale.html.supportClasses.IDataGridColumn');




/**
 * @interface
 */
org.apache.royale.html.supportClasses.IDataGridColumn = function() {
};


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('org.apache.royale.html.supportClasses.IDataGridColumn', org.apache.royale.html.supportClasses.IDataGridColumn);
/**  * @type {org.apache.royale.core.IFactory}
 */org.apache.royale.html.supportClasses.IDataGridColumn.prototype.itemRenderer;
org.apache.royale.html.supportClasses.IDataGridColumn.prototype.createColumn = function() {
};


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.html.supportClasses.IDataGridColumn.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'IDataGridColumn', qName: 'org.apache.royale.html.supportClasses.IDataGridColumn', kind: 'interface' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.html.supportClasses.IDataGridColumn.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    accessors: function () {
      return {
        'itemRenderer': { type: 'org.apache.royale.core.IFactory', access: 'readwrite', declaredBy: 'org.apache.royale.html.supportClasses.IDataGridColumn'},
        'columnWidth': { type: 'Number', access: 'readwrite', declaredBy: 'org.apache.royale.html.supportClasses.IDataGridColumn'},
        'label': { type: 'String', access: 'readwrite', declaredBy: 'org.apache.royale.html.supportClasses.IDataGridColumn'},
        'dataField': { type: 'String', access: 'readwrite', declaredBy: 'org.apache.royale.html.supportClasses.IDataGridColumn'},
        'className': { type: 'String', access: 'readwrite', declaredBy: 'org.apache.royale.html.supportClasses.IDataGridColumn'}
      };
    },
    methods: function () {
      return {
        'createColumn': { type: 'org.apache.royale.core.IUIBase', declaredBy: 'org.apache.royale.html.supportClasses.IDataGridColumn'}
      };
    }
  };
};