/**
 * Generated by Apache Royale Compiler from org\apache\royale\html\supportClasses\UIItemRendererBase.as
 * org.apache.royale.html.supportClasses.UIItemRendererBase
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('org.apache.royale.html.supportClasses.UIItemRendererBase');

goog.require('org.apache.royale.core.UIBase');
goog.require('org.apache.royale.core.ValuesManager');
goog.require('org.apache.royale.events.Event');
goog.require('org.apache.royale.utils.MXMLDataInterpreter');
goog.require('org.apache.royale.core.ISelectableItemRenderer');
goog.require('org.apache.royale.utils.Language');



/**
 *  constructor.
 *
 *  @langversion 3.0
 *  @playerversion Flash 10.2
 *  @playerversion AIR 2.6
 *  @productversion Royale 0.0
 * @constructor
 * @extends {org.apache.royale.core.UIBase}
 * @implements {org.apache.royale.core.ISelectableItemRenderer}
 */
org.apache.royale.html.supportClasses.UIItemRendererBase = function() {
  org.apache.royale.html.supportClasses.UIItemRendererBase.base(this, 'constructor');

this.useColor = this.backgroundColor;
};
goog.inherits(org.apache.royale.html.supportClasses.UIItemRendererBase, org.apache.royale.core.UIBase);


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('org.apache.royale.html.supportClasses.UIItemRendererBase', org.apache.royale.html.supportClasses.UIItemRendererBase);


/**
 * @asprivate
 * @export
 * @override
 */
org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.addedToParent = function() {
  org.apache.royale.utils.MXMLDataInterpreter.generateMXMLProperties(this, this.mxmlProperties);
  org.apache.royale.utils.MXMLDataInterpreter.generateMXMLInstances(this, this, this.MXMLDescriptor);
  org.apache.royale.html.supportClasses.UIItemRendererBase.superClass_.addedToParent.apply(this);
  this.addEventListener("widthChanged", org.apache.royale.utils.Language.closure(this.sizeChangeHandler, this, 'sizeChangeHandler'));
  this.addEventListener("heightChanged", org.apache.royale.utils.Language.closure(this.sizeChangeHandler, this, 'sizeChangeHandler'));
  this.addEventListener("sizeChanged", org.apache.royale.utils.Language.closure(this.sizeChangeHandler, this, 'sizeChangeHandler'));
  org.apache.royale.core.ValuesManager["valuesImpl"].init(this);
  this.dispatchEvent(new org.apache.royale.events.Event("initBindings"));
  this.dispatchEvent(new org.apache.royale.events.Event("initComplete"));
};


/**
 * @private
 * @type {Object}
 */
org.apache.royale.html.supportClasses.UIItemRendererBase.prototype._itemRendererParent;


/**
 * @export
 * @type {Array}
 */
org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.mxmlContent;


/**
 * @private
 * @type {Array}
 */
org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.mxmlProperties;


/**
 * @asprivate
 * @export
 * @param {Array} data
 */
org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.generateMXMLAttributes = function(data) {
  this.mxmlProperties = data;
};


/**
 * @export
 * @type {number}
 */
org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.backgroundColor = 0xFFFFFF;


/**
 * @export
 * @type {number}
 */
org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.highlightColor = 0xCEDBEF;


/**
 * @export
 * @type {number}
 */
org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.selectedColor = 0xA8C6EE;


/**
 * @export
 * @type {number}
 */
org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.downColor = 0x808080;


/**
 * @protected
 * @type {number}
 */
org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.useColor;


/**
 * @private
 * @type {Object}
 */
org.apache.royale.html.supportClasses.UIItemRendererBase.prototype._data;


/**
 * @private
 * @type {Object}
 */
org.apache.royale.html.supportClasses.UIItemRendererBase.prototype._listData;


/**
 * @private
 * @type {string}
 */
org.apache.royale.html.supportClasses.UIItemRendererBase.prototype._labelField = "label";


/**
 * @private
 * @type {number}
 */
org.apache.royale.html.supportClasses.UIItemRendererBase.prototype._index = 0;


/**
 * @private
 * @type {boolean}
 */
org.apache.royale.html.supportClasses.UIItemRendererBase.prototype._hovered;


/**
 * @private
 * @type {boolean}
 */
org.apache.royale.html.supportClasses.UIItemRendererBase.prototype._selected;


/**
 * @private
 * @type {boolean}
 */
org.apache.royale.html.supportClasses.UIItemRendererBase.prototype._down;


/**
 * @asprivate
 * @export
 */
org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.updateRenderer = function() {
  if (this.down)
    this.useColor = this.downColor;
  else if (this.hovered)
    this.useColor = this.highlightColor;
  else if (this.selected)
    this.useColor = this.selectedColor;
  else
    this.useColor = this.backgroundColor;
};


/**
 * @asprivate
 * @private
 * @param {org.apache.royale.events.Event} event
 */
org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.sizeChangeHandler = function(event) {
  this.adjustSize();
};


/**
 *  This function is called whenever the itemRenderer changes size. Sub-classes should override
 *  this method an handle the size change.
 *
 *  @langversion 3.0
 *  @playerversion Flash 10.2
 *  @playerversion AIR 2.6
 *  @productversion Royale 0.0
 * @export
 */
org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.adjustSize = function() {
};


org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.get__itemRendererParent = function() {
  return this._itemRendererParent;
};


org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.set__itemRendererParent = function(value) {
  this._itemRendererParent = value;
};


org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.get__MXMLDescriptor = function() {
  return null;
};


org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.get__data = function() {
  return this._data;
};


org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.set__data = function(value) {
  this._data = value;
};


org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.get__listData = function() {
  return this._listData;
};


org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.set__listData = function(value) {
  this._listData = value;
};


org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.get__labelField = function() {
  return this._labelField;
};


org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.set__labelField = function(value) {
  this._labelField = value;
};


org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.get__index = function() {
  return this._index;
};


org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.set__index = function(value) {
  this._index = value;
};


org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.get__hovered = function() {
  return this._hovered;
};


org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.set__hovered = function(value) {
  this._hovered = value;
  this.updateRenderer();
};


org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.get__selected = function() {
  return this._selected;
};


org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.set__selected = function(value) {
  this._selected = value;
  this.updateRenderer();
};


org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.get__down = function() {
  return this._down;
};


org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.set__down = function(value) {
  this._down = value;
  this.updateRenderer();
};


Object.defineProperties(org.apache.royale.html.supportClasses.UIItemRendererBase.prototype, /** @lends {org.apache.royale.html.supportClasses.UIItemRendererBase.prototype} */ {
/**
  * @export
  * @type {Object} */
itemRendererParent: {
get: org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.get__itemRendererParent,
set: org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.set__itemRendererParent},
/**
  * @export
  * @type {Array} */
MXMLDescriptor: {
get: org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.get__MXMLDescriptor},
/**
  * @export
  * @type {Object} */
data: {
get: org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.get__data,
set: org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.set__data},
/**
  * @export
  * @type {Object} */
listData: {
get: org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.get__listData,
set: org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.set__listData},
/**
  * @export
  * @type {string} */
labelField: {
get: org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.get__labelField,
set: org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.set__labelField},
/**
  * @export
  * @type {number} */
index: {
get: org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.get__index,
set: org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.set__index},
/**
  * @export
  * @type {boolean} */
hovered: {
get: org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.get__hovered,
set: org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.set__hovered},
/**
  * @export
  * @type {boolean} */
selected: {
get: org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.get__selected,
set: org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.set__selected},
/**
  * @export
  * @type {boolean} */
down: {
get: org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.get__down,
set: org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.set__down}}
);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'UIItemRendererBase', qName: 'org.apache.royale.html.supportClasses.UIItemRendererBase', kind: 'class' }], interfaces: [org.apache.royale.core.ISelectableItemRenderer] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.html.supportClasses.UIItemRendererBase.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {
      return {
        'mxmlContent': { type: 'Array'},
        'backgroundColor': { type: 'uint'},
        'highlightColor': { type: 'uint'},
        'selectedColor': { type: 'uint'},
        'downColor': { type: 'uint'}
      };
    },
    accessors: function () {
      return {
        'itemRendererParent': { type: 'Object', access: 'readwrite', declaredBy: 'org.apache.royale.html.supportClasses.UIItemRendererBase'},
        'MXMLDescriptor': { type: 'Array', access: 'readonly', declaredBy: 'org.apache.royale.html.supportClasses.UIItemRendererBase'},
        'data': { type: 'Object', access: 'readwrite', declaredBy: 'org.apache.royale.html.supportClasses.UIItemRendererBase', metadata: function () { return [ { name: 'Bindable', args: [ { key: '', value: '__NoChangeEvent__' } ] } ]; }},
        'listData': { type: 'Object', access: 'readwrite', declaredBy: 'org.apache.royale.html.supportClasses.UIItemRendererBase', metadata: function () { return [ { name: 'Bindable', args: [ { key: '', value: '__NoChangeEvent__' } ] } ]; }},
        'labelField': { type: 'String', access: 'readwrite', declaredBy: 'org.apache.royale.html.supportClasses.UIItemRendererBase'},
        'index': { type: 'int', access: 'readwrite', declaredBy: 'org.apache.royale.html.supportClasses.UIItemRendererBase'},
        'hovered': { type: 'Boolean', access: 'readwrite', declaredBy: 'org.apache.royale.html.supportClasses.UIItemRendererBase'},
        'selected': { type: 'Boolean', access: 'readwrite', declaredBy: 'org.apache.royale.html.supportClasses.UIItemRendererBase'},
        'down': { type: 'Boolean', access: 'readwrite', declaredBy: 'org.apache.royale.html.supportClasses.UIItemRendererBase'}
      };
    },
    methods: function () {
      return {
        'UIItemRendererBase': { type: '', declaredBy: 'org.apache.royale.html.supportClasses.UIItemRendererBase'},
        'addedToParent': { type: 'void', declaredBy: 'org.apache.royale.html.supportClasses.UIItemRendererBase'},
        'generateMXMLAttributes': { type: 'void', declaredBy: 'org.apache.royale.html.supportClasses.UIItemRendererBase', parameters: function () { return [  { index: 1, type: 'Array', optional: false } ]; }},
        'updateRenderer': { type: 'void', declaredBy: 'org.apache.royale.html.supportClasses.UIItemRendererBase'},
        'adjustSize': { type: 'void', declaredBy: 'org.apache.royale.html.supportClasses.UIItemRendererBase'}
      };
    },
    metadata: function () { return [  ]; }
  };
};