/**
 * Generated by Apache Royale Compiler from org\apache\royale\html\Container.as
 * org.apache.royale.html.Container
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('org.apache.royale.html.Container');

goog.require('org.apache.royale.core.ContainerBase');
goog.require('org.apache.royale.core.ValuesManager');
goog.require('org.apache.royale.events.Event');
goog.require('org.apache.royale.utils.MXMLDataInterpreter');
goog.require('org.apache.royale.core.IMXMLDocument');



/**
 *  Constructor.
 *  
 *  @langversion 3.0
 *  @playerversion Flash 10.2
 *  @playerversion AIR 2.6
 *  @productversion Royale 0.0
 * @constructor
 * @extends {org.apache.royale.core.ContainerBase}
 * @implements {org.apache.royale.core.IMXMLDocument}
 */
org.apache.royale.html.Container = function() {
  
  this._mxmlDocument = this;
  this.typeNames = 'Container';
  org.apache.royale.html.Container.base(this, 'constructor');
};
goog.inherits(org.apache.royale.html.Container, org.apache.royale.core.ContainerBase);


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('org.apache.royale.html.Container', org.apache.royale.html.Container);


/**
 * @private
 * @type {Array}
 */
org.apache.royale.html.Container.prototype._mxmlDescriptor;


/**
 * @private
 * @type {Object}
 */
org.apache.royale.html.Container.prototype._mxmlDocument;


/**
 * @private
 * @type {boolean}
 */
org.apache.royale.html.Container.prototype._initialized;


/**
 * @asprivate
 * @export
 * @override
 */
org.apache.royale.html.Container.prototype.addedToParent = function() {
  if (!this._initialized) {
    org.apache.royale.core.ValuesManager["valuesImpl"].init(this);
  }
  org.apache.royale.html.Container.superClass_.addedToParent.apply(this);
  if (!this._initialized) {
    org.apache.royale.utils.MXMLDataInterpreter.generateMXMLInstances(this._mxmlDocument, this, this.MXMLDescriptor);
    this.dispatchEvent(new org.apache.royale.events.Event("initBindings"));
    this.dispatchEvent(new org.apache.royale.events.Event("initComplete"));
    this._initialized = true;
  }
};


/**
 *  @asprivate
 * @export
 * @param {Object} document
 * @param {Array} value
 */
org.apache.royale.html.Container.prototype.setMXMLDescriptor = function(document, value) {
  this._mxmlDocument = document;
  this._mxmlDescriptor = value;
};


/**
 *  @copy org.apache.royale.core.Application#generateMXMLAttributes()
 *  
 *  @langversion 3.0
 *  @playerversion Flash 10.2
 *  @playerversion AIR 2.6
 *  @productversion Royale 0.8
 * @export
 * @param {Array} data
 */
org.apache.royale.html.Container.prototype.generateMXMLAttributes = function(data) {
  org.apache.royale.utils.MXMLDataInterpreter.generateMXMLProperties(this, data);
};


/**
 * @export
 * @type {Array}
 */
org.apache.royale.html.Container.prototype.mxmlContent;


org.apache.royale.html.Container.prototype.get__MXMLDescriptor = function() {
  return this._mxmlDescriptor;
};


Object.defineProperties(org.apache.royale.html.Container.prototype, /** @lends {org.apache.royale.html.Container.prototype} */ {
/**
  * @export
  * @type {Array} */
MXMLDescriptor: {
get: org.apache.royale.html.Container.prototype.get__MXMLDescriptor}}
);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.html.Container.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'Container', qName: 'org.apache.royale.html.Container', kind: 'class' }], interfaces: [org.apache.royale.core.IMXMLDocument] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.html.Container.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {
      return {
        'mxmlContent': { type: 'Array'}
      };
    },
    accessors: function () {
      return {
        'MXMLDescriptor': { type: 'Array', access: 'readonly', declaredBy: 'org.apache.royale.html.Container'}
      };
    },
    methods: function () {
      return {
        'Container': { type: '', declaredBy: 'org.apache.royale.html.Container'},
        'addedToParent': { type: 'void', declaredBy: 'org.apache.royale.html.Container'},
        'setMXMLDescriptor': { type: 'void', declaredBy: 'org.apache.royale.html.Container', parameters: function () { return [  { index: 1, type: 'Object', optional: false },{ index: 2, type: 'Array', optional: false } ]; }},
        'generateMXMLAttributes': { type: 'void', declaredBy: 'org.apache.royale.html.Container', parameters: function () { return [  { index: 1, type: 'Array', optional: false } ]; }}
      };
    },
    metadata: function () { return [  ]; }
  };
};