/**
 * Generated by Apache Royale Compiler from org\apache\royale\html\DataGridButtonBar.as
 * org.apache.royale.html.DataGridButtonBar
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('org.apache.royale.html.DataGridButtonBar');

goog.require('org.apache.royale.html.ButtonBar');



/**
 *  constructor.
 *
 *  @langversion 3.0
 *  @playerversion Flash 10.2
 *  @playerversion AIR 2.6
 *  @productversion Royale 0.0
 * @constructor
 * @extends {org.apache.royale.html.ButtonBar}
 */
org.apache.royale.html.DataGridButtonBar = function() {
  org.apache.royale.html.DataGridButtonBar.base(this, 'constructor');
  this.className = "DataGridButtonBar";
};
goog.inherits(org.apache.royale.html.DataGridButtonBar, org.apache.royale.html.ButtonBar);


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('org.apache.royale.html.DataGridButtonBar', org.apache.royale.html.DataGridButtonBar);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.html.DataGridButtonBar.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'DataGridButtonBar', qName: 'org.apache.royale.html.DataGridButtonBar', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.html.DataGridButtonBar.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {return {};},
    methods: function () {
      return {
        'DataGridButtonBar': { type: '', declaredBy: 'org.apache.royale.html.DataGridButtonBar'}
      };
    }
  };
};