/**
 * Generated by Apache Royale Compiler from org\apache\royale\html\beads\models\SingleSelectionCollectionViewModel.as
 * org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel');

goog.require('org.apache.royale.collections.ICollectionView');
goog.require('org.apache.royale.events.Event');
goog.require('org.apache.royale.events.EventDispatcher');
goog.require('org.apache.royale.core.IRollOverModel');
goog.require('org.apache.royale.core.ISelectionModel');
goog.require('org.apache.royale.utils.Language');



/**
 *  Constructor.
 *
 *  @langversion 3.0
 *  @playerversion Flash 10.2
 *  @playerversion AIR 2.6
 *  @productversion Royale 0.0
 * @constructor
 * @extends {org.apache.royale.events.EventDispatcher}
 * @implements {org.apache.royale.core.ISelectionModel}
 * @implements {org.apache.royale.core.IRollOverModel}
 */
org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel = function() {
  org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.base(this, 'constructor');
};
goog.inherits(org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel, org.apache.royale.events.EventDispatcher);


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel', org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel);


/**
 * @private
 * @type {org.apache.royale.core.IStrand}
 */
org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype._strand;


/**
 * @private
 * @type {org.apache.royale.collections.ICollectionView}
 */
org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype._dataProvider;


/**
 * @private
 * @type {number}
 */
org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype._selectedIndex = -1;


/**
 * @private
 * @type {number}
 */
org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype._rollOverIndex = -1;


/**
 * @private
 * @type {string}
 */
org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype._labelField = null;


/**
 * @private
 * @type {Object}
 */
org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype._selectedItem;


/**
 * @private
 * @type {string}
 */
org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype._selectedString;


org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.set__strand = function(value) {
  this._strand = value;
};


org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.get__dataProvider = function() {
  return this._dataProvider;
};


org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.set__dataProvider = function(value) {
  if (value == this._dataProvider)
    return;
  this._dataProvider = org.apache.royale.utils.Language.as(value, org.apache.royale.collections.ICollectionView);
  if (!this._dataProvider || this._selectedIndex >= this._dataProvider.length)
    this._selectedIndex = -1;
  this._selectedItem = this._selectedIndex == -1 ? null : this._dataProvider.getItemAt(this._selectedIndex);
  this.dispatchEvent(new org.apache.royale.events.Event("dataProviderChanged"));
};


org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.get__labelField = function() {
  return this._labelField;
};


org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.set__labelField = function(value) {
  if (value != this._labelField) {
    this._labelField = value;
    this.dispatchEvent(new org.apache.royale.events.Event("labelFieldChanged"));
  }
};


org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.get__selectedIndex = function() {
  return this._selectedIndex;
};


org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.set__selectedIndex = function(value) {
  if (value == this._selectedIndex)
    return;
  this._selectedIndex = value;
  this._selectedItem = (value == -1 || this._dataProvider == null) ? null : (value < this._dataProvider.length) ? this._dataProvider.getItemAt(value) : null;
  this.dispatchEvent(new org.apache.royale.events.Event("selectedIndexChanged"));
};


org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.get__rollOverIndex = function() {
  return this._rollOverIndex;
};


org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.set__rollOverIndex = function(value) {
  if (value != this._rollOverIndex) {
    this._rollOverIndex = value;
    this.dispatchEvent(new org.apache.royale.events.Event("rollOverIndexChanged"));
  }
};


org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.get__selectedItem = function() {
  return this._selectedItem;
};


org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.set__selectedItem = function(value) {
  if (value == this._selectedItem)
    return;
  this._selectedItem = value;
  var /** @type {number} */ n = this._dataProvider.length;
  for (var /** @type {number} */ i = 0; i < n; i++) {
    if (this._dataProvider.getItemAt(i) == value) {
      this._selectedIndex = i;
      break;
    }
  }
  this.dispatchEvent(new org.apache.royale.events.Event("selectedItemChanged"));
  this.dispatchEvent(new org.apache.royale.events.Event("selectedIndexChanged"));
};


org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.get__selectedString = function() {
  return String(this._selectedItem);
};


org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.set__selectedString = function(value) {
  this._selectedString = value;
  var /** @type {number} */ n = this._dataProvider.length;
  for (var /** @type {number} */ i = 0; i < n; i++) {
    if (String(this._dataProvider.getItemAt(i)) == value) {
      this._selectedIndex = i;
      break;
    }
  }
  this.dispatchEvent(new org.apache.royale.events.Event("selectedItemChanged"));
  this.dispatchEvent(new org.apache.royale.events.Event("selectedIndexChanged"));
};


Object.defineProperties(org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype, /** @lends {org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype} */ {
/**
  * @export
  * @type {org.apache.royale.core.IStrand} */
strand: {
set: org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.set__strand},
/**
  * @export
  * @type {Object} */
dataProvider: {
get: org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.get__dataProvider,
set: org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.set__dataProvider},
/**
  * @export
  * @type {string} */
labelField: {
get: org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.get__labelField,
set: org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.set__labelField},
/**
  * @export
  * @type {number} */
selectedIndex: {
get: org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.get__selectedIndex,
set: org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.set__selectedIndex},
/**
  * @export
  * @type {number} */
rollOverIndex: {
get: org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.get__rollOverIndex,
set: org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.set__rollOverIndex},
/**
  * @export
  * @type {Object} */
selectedItem: {
get: org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.get__selectedItem,
set: org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.set__selectedItem},
/**
  * @export
  * @type {string} */
selectedString: {
get: org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.get__selectedString,
set: org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.set__selectedString}}
);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'SingleSelectionCollectionViewModel', qName: 'org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel', kind: 'class' }], interfaces: [org.apache.royale.core.ISelectionModel, org.apache.royale.core.IRollOverModel] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {
      return {
        'strand': { type: 'org.apache.royale.core.IStrand', access: 'writeonly', declaredBy: 'org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel'},
        'dataProvider': { type: 'Object', access: 'readwrite', declaredBy: 'org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel'},
        'labelField': { type: 'String', access: 'readwrite', declaredBy: 'org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel'},
        'selectedIndex': { type: 'int', access: 'readwrite', declaredBy: 'org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel'},
        'rollOverIndex': { type: 'int', access: 'readwrite', declaredBy: 'org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel'},
        'selectedItem': { type: 'Object', access: 'readwrite', declaredBy: 'org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel'},
        'selectedString': { type: 'String', access: 'readwrite', declaredBy: 'org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel'}
      };
    },
    methods: function () {
      return {
        'SingleSelectionCollectionViewModel': { type: '', declaredBy: 'org.apache.royale.html.beads.models.SingleSelectionCollectionViewModel'}
      };
    }
  };
};