/**
 * Generated by Apache Royale Compiler from org/apache/royale/html/util/getModelByType.as
 * org.apache.royale.html.util.getModelByType
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('org.apache.royale.html.util.getModelByType');
/* Royale Dependency List: org.apache.royale.core.IBeadModel,org.apache.royale.core.IStrand,org.apache.royale.core.IStrandWithModel,org.apache.royale.utils.Language,XML*/




/**
 * @royaleignorecoercion org.apache.royale.core.IBeadModel
 * @royaleignorecoercion org.apache.royale.core.IStrandWithModel
 * @param {org.apache.royale.core.IStrand} strand
 * @param {Object} type
 * @return {Object}
 */
org.apache.royale.html.util.getModelByType = function(strand, type) {
  var /** @type {Object} */ strandWithModel = strand;
  if (org.apache.royale.utils.Language.is(strandWithModel.model, type))
    return strandWithModel.model;
  return strand.getBeadByType(type);
}
