/**
 * Generated by Apache Royale Compiler from org/apache/royale/routing/HashChangeNotifierBead.as
 * org.apache.royale.routing.HashChangeNotifierBead
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('org.apache.royale.routing.HashChangeNotifierBead');
/* Royale Dependency List: org.apache.royale.core.IStrand,org.apache.royale.events.Event,org.apache.royale.utils.Language,XML*/

goog.require('org.apache.royale.events.EventDispatcher');
goog.require('org.apache.royale.core.IBead');



/**
 *  constructor.
 *
 *  @langversion 3.0
 *  @playerversion Flash 10.2
 *  @playerversion AIR 2.6
 *  @productversion Royale 0.9
 * @constructor
 * @extends {org.apache.royale.events.EventDispatcher}
 * @implements {org.apache.royale.core.IBead}
 */
org.apache.royale.routing.HashChangeNotifierBead = function() {
  org.apache.royale.routing.HashChangeNotifierBead.base(this, 'constructor');
};
goog.inherits(org.apache.royale.routing.HashChangeNotifierBead, org.apache.royale.events.EventDispatcher);


/**
 * @private
 * @type {org.apache.royale.core.IStrand}
 */
org.apache.royale.routing.HashChangeNotifierBead.prototype.org_apache_royale_routing_HashChangeNotifierBead__strand;


/**
 * @private
 */
org.apache.royale.routing.HashChangeNotifierBead.prototype.org_apache_royale_routing_HashChangeNotifierBead_hashChangeHandler = function() {
  this.dispatchEvent(new org.apache.royale.events.Event("hashChange"));
};


/**
 * @nocollapse
 * @export
 * @type {org.apache.royale.core.IStrand}
 */
org.apache.royale.routing.HashChangeNotifierBead.prototype.strand;


org.apache.royale.routing.HashChangeNotifierBead.prototype.set__strand = function(value) {
  this.org_apache_royale_routing_HashChangeNotifierBead__strand = value;
  window.addEventListener("hashchange", org.apache.royale.utils.Language.closure(this.org_apache_royale_routing_HashChangeNotifierBead_hashChangeHandler, this, 'org_apache_royale_routing_HashChangeNotifierBead_hashChangeHandler'));
};


/**
 * @nocollapse
 * @export
 * @type {string}
 */
org.apache.royale.routing.HashChangeNotifierBead.prototype.hash;


org.apache.royale.routing.HashChangeNotifierBead.prototype.get__hash = function() {
  return location.hash;
  
};


Object.defineProperties(org.apache.royale.routing.HashChangeNotifierBead.prototype, /** @lends {org.apache.royale.routing.HashChangeNotifierBead.prototype} */ {
/**
 * @type {org.apache.royale.core.IStrand}
 */
strand: {
set: org.apache.royale.routing.HashChangeNotifierBead.prototype.set__strand},
/**
 * @type {string}
 */
hash: {
get: org.apache.royale.routing.HashChangeNotifierBead.prototype.get__hash}}
);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.routing.HashChangeNotifierBead.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'HashChangeNotifierBead', qName: 'org.apache.royale.routing.HashChangeNotifierBead', kind: 'class' }], interfaces: [org.apache.royale.core.IBead] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.routing.HashChangeNotifierBead.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    accessors: function () {
      return {
        'strand': { type: 'org.apache.royale.core.IStrand', access: 'writeonly', declaredBy: 'org.apache.royale.routing.HashChangeNotifierBead'},
        'hash': { type: 'String', access: 'readonly', declaredBy: 'org.apache.royale.routing.HashChangeNotifierBead'}
      };
    },
    methods: function () {
      return {
        'HashChangeNotifierBead': { type: '', declaredBy: 'org.apache.royale.routing.HashChangeNotifierBead'}
      };
    }
  };
};
/**
 * @const
 * @type {number}
 */
org.apache.royale.routing.HashChangeNotifierBead.prototype.ROYALE_COMPILE_FLAGS = 10;

//# sourceMappingURL=./HashChangeNotifierBead.js.map
