/**
 * Generated by Apache Royale Compiler from org/apache/royale/html/beads/ItemRendererFactoryBase.as
 * org.apache.royale.html.beads.ItemRendererFactoryBase
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('org.apache.royale.html.beads.ItemRendererFactoryBase');
/* Royale Dependency List: org.apache.royale.core.IDataProviderModel,org.apache.royale.core.IItemRendererClassFactory,org.apache.royale.core.IItemRendererInitializer,org.apache.royale.core.IItemRendererOwnerView,org.apache.royale.core.IStrand,org.apache.royale.events.Event,org.apache.royale.events.IEventDispatcher,org.apache.royale.html.util.getModelByType,org.apache.royale.utils.loadBeadFromValuesManager,org.apache.royale.utils.Language,XML*/

goog.require('org.apache.royale.core.DispatcherBead');



/**
 *  Constructor.
 *  
 *  @langversion 3.0
 *  @playerversion Flash 10.2
 *  @playerversion AIR 2.6
 *  @productversion Royale 0.8
 * @constructor
 * @extends {org.apache.royale.core.DispatcherBead}
 * @param {Object=} target
 */
org.apache.royale.html.beads.ItemRendererFactoryBase = function(target) {
  target = typeof target !== 'undefined' ? target : null;
  org.apache.royale.html.beads.ItemRendererFactoryBase.base(this, 'constructor', org.apache.royale.utils.Language.as(target, org.apache.royale.events.IEventDispatcher, true));
};
goog.inherits(org.apache.royale.html.beads.ItemRendererFactoryBase, org.apache.royale.core.DispatcherBead);


/**
 * @protected
 * @type {org.apache.royale.core.IDataProviderModel}
 */
org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.dataProviderModel;


/**
 * @asprivate
 * @royaleignorecoercion org.apache.royale.core.IDataProviderModel
 * @royaleignorecoercion org.apache.royale.core.IItemRendererClassFactory
 * @royaleignorecoercion org.apache.royale.html.beads.DataFieldProviderBead
 * @royaleignorecoercion org.apache.royale.events.IEventDispatcher
 * @protected
 * @param {org.apache.royale.events.Event} event
 */
org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.finishSetup = function(event) {
  this._strand.removeEventListener("initComplete", org.apache.royale.utils.Language.closure(this.finishSetup, this, 'finishSetup'));
  this.dataProviderModel = org.apache.royale.html.util.getModelByType(this._strand, org.apache.royale.core.IDataProviderModel);
  this.dataProviderModel.addEventListener("dataProviderChanged", org.apache.royale.utils.Language.closure(this.dataProviderChangeHandler, this, 'dataProviderChangeHandler'));
  if (!this.org_apache_royale_html_beads_ItemRendererFactoryBase__itemRendererFactory)
    this.org_apache_royale_html_beads_ItemRendererFactoryBase__itemRendererFactory = org.apache.royale.utils.loadBeadFromValuesManager(org.apache.royale.core.IItemRendererClassFactory, "iItemRendererClassFactory", this._strand);
  this.dataProviderChangeHandler(null);
};


/**
 * @private
 * @type {Object}
 */
org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.org_apache_royale_html_beads_ItemRendererFactoryBase__itemRendererFactory;


/**
 * @private
 * @type {org.apache.royale.core.IItemRendererInitializer}
 */
org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.org_apache_royale_html_beads_ItemRendererFactoryBase__itemRendererInitializer;


/**
 *  This Factory deletes all renderers, and generates a renderer
 *  for every data provider item.
 *  
 *  @langversion 3.0
 *  @playerversion Flash 10.2
 *  @playerversion AIR 2.6
 *  @productversion Royale 0.8
 * @protected
 * @param {org.apache.royale.events.Event} event
 */
org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.dataProviderChangeHandler = function(event) {
};


/**
 *  Remove all itemrenderers
 * 
 *  @royaleignorecoercion org.apache.royale.core.IItemRendererOwnerView
 * @protected
 * @param {Object} dataGroup
 */
org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.removeAllItemRenderers = function(dataGroup) {
  dataGroup.removeAllItemRenderers();
};


/**
 * @protected
 * @param {number} i
 * @return {Object}
 */
org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.getItemAt = function(i) {
  return null;
};


org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.set__strand = function(value) {
  this._strand = value;
  this.listenOnStrand("initComplete", org.apache.royale.utils.Language.closure(this.finishSetup, this, 'finishSetup'));
};


/**
 * @nocollapse
 * @export
 * @type {org.apache.royale.core.IItemRendererClassFactory}
 */
org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.itemRendererFactory;


org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.get__itemRendererFactory = function() {
  if (!this.org_apache_royale_html_beads_ItemRendererFactoryBase__itemRendererFactory)
    this.org_apache_royale_html_beads_ItemRendererFactoryBase__itemRendererFactory = org.apache.royale.utils.loadBeadFromValuesManager(org.apache.royale.core.IItemRendererClassFactory, "iItemRendererClassFactory", this._strand);
  return this.org_apache_royale_html_beads_ItemRendererFactoryBase__itemRendererFactory;
};


org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.set__itemRendererFactory = function(value) {
  this.org_apache_royale_html_beads_ItemRendererFactoryBase__itemRendererFactory = value;
};


/**
 * @nocollapse
 * @export
 * @type {org.apache.royale.core.IItemRendererInitializer}
 */
org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.itemRendererInitializer;


org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.get__itemRendererInitializer = function() {
  if (!this.org_apache_royale_html_beads_ItemRendererFactoryBase__itemRendererInitializer)
    this.org_apache_royale_html_beads_ItemRendererFactoryBase__itemRendererInitializer = org.apache.royale.utils.loadBeadFromValuesManager(org.apache.royale.core.IItemRendererInitializer, "iItemRendererInitializer", this._strand);
  return this.org_apache_royale_html_beads_ItemRendererFactoryBase__itemRendererInitializer;
};


org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.set__itemRendererInitializer = function(value) {
  this.org_apache_royale_html_beads_ItemRendererFactoryBase__itemRendererInitializer = value;
};


/**
 * @nocollapse
 * @type {number}
 */
org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.dataProviderLength;


org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.get__dataProviderLength = function() {
  return 0;
};


Object.defineProperties(org.apache.royale.html.beads.ItemRendererFactoryBase.prototype, /** @lends {org.apache.royale.html.beads.ItemRendererFactoryBase.prototype} */ {
/**
 * @type {org.apache.royale.core.IStrand}
 */
strand: {
set: org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.set__strand},
/**
 * @type {org.apache.royale.core.IItemRendererClassFactory}
 */
itemRendererFactory: {
get: org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.get__itemRendererFactory,
set: org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.set__itemRendererFactory},
/**
 * @type {org.apache.royale.core.IItemRendererInitializer}
 */
itemRendererInitializer: {
get: org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.get__itemRendererInitializer,
set: org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.set__itemRendererInitializer},
/**
 * @type {number}
 */
dataProviderLength: {
get: org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.get__dataProviderLength}}
);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'ItemRendererFactoryBase', qName: 'org.apache.royale.html.beads.ItemRendererFactoryBase', kind: 'class' }] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    accessors: function () {
      return {
        'strand': { type: 'org.apache.royale.core.IStrand', access: 'writeonly', declaredBy: 'org.apache.royale.html.beads.ItemRendererFactoryBase'},
        'itemRendererFactory': { type: 'org.apache.royale.core.IItemRendererClassFactory', access: 'readwrite', declaredBy: 'org.apache.royale.html.beads.ItemRendererFactoryBase'},
        'itemRendererInitializer': { type: 'org.apache.royale.core.IItemRendererInitializer', access: 'readwrite', declaredBy: 'org.apache.royale.html.beads.ItemRendererFactoryBase'}
      };
    },
    methods: function () {
      return {
        'ItemRendererFactoryBase': { type: '', declaredBy: 'org.apache.royale.html.beads.ItemRendererFactoryBase', parameters: function () { return [ 'Object', true ]; }}
      };
    }
  };
};
/**
 * @const
 * @type {number}
 */
org.apache.royale.html.beads.ItemRendererFactoryBase.prototype.ROYALE_COMPILE_FLAGS = 10;

//# sourceMappingURL=./ItemRendererFactoryBase.js.map
