/**
 * Generated by Apache Royale Compiler from org\apache\royale\html\beads\ITextItemRenderer.as
 * org.apache.royale.html.beads.ITextItemRenderer
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('org.apache.royale.html.beads.ITextItemRenderer');

goog.require('org.apache.royale.core.ISelectableItemRenderer');



/**
 * @interface
 * @extends {org.apache.royale.core.ISelectableItemRenderer}
 */
org.apache.royale.html.beads.ITextItemRenderer = function() {
};


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('org.apache.royale.html.beads.ITextItemRenderer', org.apache.royale.html.beads.ITextItemRenderer);
/**  * @type {string}
 */org.apache.royale.html.beads.ITextItemRenderer.prototype.text;


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.html.beads.ITextItemRenderer.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'ITextItemRenderer', qName: 'org.apache.royale.html.beads.ITextItemRenderer', kind: 'interface' }], interfaces: [org.apache.royale.core.ISelectableItemRenderer] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.html.beads.ITextItemRenderer.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    accessors: function () {
      return {
        'text': { type: 'String', access: 'readwrite', declaredBy: 'org.apache.royale.html.beads.ITextItemRenderer'}
      };
    },
    methods: function () {return {};}
  };
};