/**
 * Generated by Apache Royale Compiler from org/apache/royale/html/beads/SelectableItemRendererBeadBase.as
 * org.apache.royale.html.beads.SelectableItemRendererBeadBase
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('org.apache.royale.html.beads.SelectableItemRendererBeadBase');
/* Royale Dependency List: org.apache.royale.core.IStrand,org.apache.royale.events.Event,org.apache.royale.events.IEventDispatcher,org.apache.royale.utils.Language*/

goog.require('org.apache.royale.core.IBead');
goog.require('org.apache.royale.core.ISelectableItemRenderer');



/**
 *  constructor.
 *
 *  @langversion 3.0
 *  @playerversion Flash 10.2
 *  @playerversion AIR 2.6
 *  @productversion Royale 0.8
 * @constructor
 * @implements {org.apache.royale.core.IBead}
 * @implements {org.apache.royale.core.ISelectableItemRenderer}
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase = function() {

this.useColor = this.backgroundColor;
};


/**
 * @protected
 * @type {org.apache.royale.core.IStrand}
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype._strand;


/**
 * @private
 * @type {number}
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.org_apache_royale_html_beads_SelectableItemRendererBeadBase__backgroundColor = 0xffffff;


/**
 * @private
 * @type {number}
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.org_apache_royale_html_beads_SelectableItemRendererBeadBase__highlightColor = 0xcedbef;


/**
 * @private
 * @type {number}
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.org_apache_royale_html_beads_SelectableItemRendererBeadBase__selectedColor = 0xa8c6ee;


/**
 * @private
 * @type {number}
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.org_apache_royale_html_beads_SelectableItemRendererBeadBase__downColor = 0x808080;


/**
 * @protected
 * @type {number}
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.useColor;


/**
 * @private
 * @type {boolean}
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.org_apache_royale_html_beads_SelectableItemRendererBeadBase__hovered;


/**
 * @private
 * @type {boolean}
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.org_apache_royale_html_beads_SelectableItemRendererBeadBase__selected;


/**
 * @private
 * @type {boolean}
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.org_apache_royale_html_beads_SelectableItemRendererBeadBase__down;


/**
 * @asprivate
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.updateRenderer = function() {
  if (this.down)
    this.useColor = this.downColor;
  else if (this.hovered)
    this.useColor = this.highlightColor;
  else if (this.selected)
    this.useColor = this.selectedColor;
  else
    this.useColor = this.backgroundColor;
};


/**
 * @asprivate
 * @private
 * @param {org.apache.royale.events.Event} event
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.org_apache_royale_html_beads_SelectableItemRendererBeadBase_sizeChangeHandler = function(event) {
  this.adjustSize();
};


/**
 *  This function is called whenever the itemRenderer changes size. Sub-classes should override
 *  this method an handle the size change.
 *
 *  @langversion 3.0
 *  @playerversion Flash 10.2
 *  @playerversion AIR 2.6
 *  @productversion Royale 0.0
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.adjustSize = function() {
};


/**
 * @nocollapse
 * @export
 * @type {org.apache.royale.core.IStrand}
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.strand;


org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.set__strand = function(value) {
  this._strand = value;
  var /** @type {org.apache.royale.events.IEventDispatcher} */ host = value;
  host.addEventListener("widthChanged", org.apache.royale.utils.Language.closure(this.org_apache_royale_html_beads_SelectableItemRendererBeadBase_sizeChangeHandler, this, 'org_apache_royale_html_beads_SelectableItemRendererBeadBase_sizeChangeHandler'));
  host.addEventListener("heightChanged", org.apache.royale.utils.Language.closure(this.org_apache_royale_html_beads_SelectableItemRendererBeadBase_sizeChangeHandler, this, 'org_apache_royale_html_beads_SelectableItemRendererBeadBase_sizeChangeHandler'));
  host.addEventListener("sizeChanged", org.apache.royale.utils.Language.closure(this.org_apache_royale_html_beads_SelectableItemRendererBeadBase_sizeChangeHandler, this, 'org_apache_royale_html_beads_SelectableItemRendererBeadBase_sizeChangeHandler'));
};


/**
 * @nocollapse
 * @export
 * @type {number}
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.backgroundColor;


org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.get__backgroundColor = function() {
  return this.org_apache_royale_html_beads_SelectableItemRendererBeadBase__backgroundColor;
};


org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.set__backgroundColor = function(value) {
  this.org_apache_royale_html_beads_SelectableItemRendererBeadBase__backgroundColor = value;
};


/**
 * @nocollapse
 * @export
 * @type {number}
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.highlightColor;


org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.get__highlightColor = function() {
  return this.org_apache_royale_html_beads_SelectableItemRendererBeadBase__highlightColor;
};


org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.set__highlightColor = function(value) {
  this.org_apache_royale_html_beads_SelectableItemRendererBeadBase__highlightColor = value;
};


/**
 * @nocollapse
 * @export
 * @type {number}
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.selectedColor;


org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.get__selectedColor = function() {
  return this.org_apache_royale_html_beads_SelectableItemRendererBeadBase__selectedColor;
};


org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.set__selectedColor = function(value) {
  this.org_apache_royale_html_beads_SelectableItemRendererBeadBase__selectedColor = value;
};


/**
 * @nocollapse
 * @export
 * @type {number}
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.downColor;


org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.get__downColor = function() {
  return this.org_apache_royale_html_beads_SelectableItemRendererBeadBase__downColor;
};


org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.set__downColor = function(value) {
  this.org_apache_royale_html_beads_SelectableItemRendererBeadBase__downColor = value;
};


/**
 * @nocollapse
 * @export
 * @type {boolean}
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.hovered;


org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.get__hovered = function() {
  return this.org_apache_royale_html_beads_SelectableItemRendererBeadBase__hovered;
};


org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.set__hovered = function(value) {
  this.org_apache_royale_html_beads_SelectableItemRendererBeadBase__hovered = value;
  this.updateRenderer();
};


/**
 * @nocollapse
 * @export
 * @type {boolean}
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.selected;


org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.get__selected = function() {
  return this.org_apache_royale_html_beads_SelectableItemRendererBeadBase__selected;
};


org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.set__selected = function(value) {
  this.org_apache_royale_html_beads_SelectableItemRendererBeadBase__selected = value;
  this.updateRenderer();
};


/**
 * @nocollapse
 * @export
 * @type {boolean}
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.down;


org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.get__down = function() {
  return this.org_apache_royale_html_beads_SelectableItemRendererBeadBase__down;
};


org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.set__down = function(value) {
  this.org_apache_royale_html_beads_SelectableItemRendererBeadBase__down = value;
  this.updateRenderer();
};


Object.defineProperties(org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype, /** @lends {org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype} */ {
/**
 * @type {org.apache.royale.core.IStrand}
 */
strand: {
set: org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.set__strand},
/**
 * @type {number}
 */
backgroundColor: {
get: org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.get__backgroundColor,
set: org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.set__backgroundColor},
/**
 * @type {number}
 */
highlightColor: {
get: org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.get__highlightColor,
set: org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.set__highlightColor},
/**
 * @type {number}
 */
selectedColor: {
get: org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.get__selectedColor,
set: org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.set__selectedColor},
/**
 * @type {number}
 */
downColor: {
get: org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.get__downColor,
set: org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.set__downColor},
/**
 * @type {boolean}
 */
hovered: {
get: org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.get__hovered,
set: org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.set__hovered},
/**
 * @type {boolean}
 */
selected: {
get: org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.get__selected,
set: org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.set__selected},
/**
 * @type {boolean}
 */
down: {
get: org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.get__down,
set: org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.set__down}}
);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'SelectableItemRendererBeadBase', qName: 'org.apache.royale.html.beads.SelectableItemRendererBeadBase', kind: 'class' }], interfaces: [org.apache.royale.core.IBead, org.apache.royale.core.ISelectableItemRenderer] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    accessors: function () {
      return {
        'strand': { type: 'org.apache.royale.core.IStrand', access: 'writeonly', declaredBy: 'org.apache.royale.html.beads.SelectableItemRendererBeadBase'},
        'backgroundColor': { type: 'uint', access: 'readwrite', declaredBy: 'org.apache.royale.html.beads.SelectableItemRendererBeadBase'},
        'highlightColor': { type: 'uint', access: 'readwrite', declaredBy: 'org.apache.royale.html.beads.SelectableItemRendererBeadBase'},
        'selectedColor': { type: 'uint', access: 'readwrite', declaredBy: 'org.apache.royale.html.beads.SelectableItemRendererBeadBase'},
        'downColor': { type: 'uint', access: 'readwrite', declaredBy: 'org.apache.royale.html.beads.SelectableItemRendererBeadBase'},
        'hovered': { type: 'Boolean', access: 'readwrite', declaredBy: 'org.apache.royale.html.beads.SelectableItemRendererBeadBase'},
        'selected': { type: 'Boolean', access: 'readwrite', declaredBy: 'org.apache.royale.html.beads.SelectableItemRendererBeadBase'},
        'down': { type: 'Boolean', access: 'readwrite', declaredBy: 'org.apache.royale.html.beads.SelectableItemRendererBeadBase'}
      };
    },
    methods: function () {
      return {
        'SelectableItemRendererBeadBase': { type: '', declaredBy: 'org.apache.royale.html.beads.SelectableItemRendererBeadBase'},
        'updateRenderer': { type: 'void', declaredBy: 'org.apache.royale.html.beads.SelectableItemRendererBeadBase'},
        'adjustSize': { type: 'void', declaredBy: 'org.apache.royale.html.beads.SelectableItemRendererBeadBase'}
      };
    }
  };
};
/**
 * @const
 * @type {number}
 */
org.apache.royale.html.beads.SelectableItemRendererBeadBase.prototype.ROYALE_COMPILE_FLAGS = 10;

//# sourceMappingURL=./SelectableItemRendererBeadBase.js.map
