/**
 * Generated by Apache Royale Compiler from org\apache\royale\html\beads\layouts\DataGridLayout.as
 * org.apache.royale.html.beads.layouts.DataGridLayout
 *
 * @fileoverview
 *
 * @suppress {checkTypes|accessControls}
 */

goog.provide('org.apache.royale.html.beads.layouts.DataGridLayout');

goog.require('org.apache.royale.core.IDataGridModel');
goog.require('org.apache.royale.core.IUIBase');
goog.require('org.apache.royale.core.UIBase');
goog.require('org.apache.royale.events.Event');
goog.require('org.apache.royale.events.IEventDispatcher');
goog.require('org.apache.royale.html.beads.IDataGridView');
goog.require('org.apache.royale.html.beads.models.ButtonBarModel');
goog.require('org.apache.royale.html.supportClasses.IDataGridColumn');
goog.require('org.apache.royale.utils.CSSContainerUtils');
goog.require('org.apache.royale.core.IBeadLayout');
goog.require('org.apache.royale.utils.Language');



/**
 *  constructor
 *  
 *  @langversion 3.0
 *  @playerversion Flash 10.2
 *  @playerversion AIR 2.6
 *  @productversion Royale 0.0
 * @constructor
 * @implements {org.apache.royale.core.IBeadLayout}
 */
org.apache.royale.html.beads.layouts.DataGridLayout = function() {
};


/**
 * Prevent renaming of class. Needed for reflection.
 */
goog.exportSymbol('org.apache.royale.html.beads.layouts.DataGridLayout', org.apache.royale.html.beads.layouts.DataGridLayout);


/**
 * @private
 * @type {org.apache.royale.core.IStrand}
 */
org.apache.royale.html.beads.layouts.DataGridLayout.prototype._strand;


/**
 * @private
 * @param {org.apache.royale.events.Event} event
 */
org.apache.royale.html.beads.layouts.DataGridLayout.prototype.handleSizeChanges = function(event) {
  this.layout();
};


/**
 * @private
 * @param {org.apache.royale.events.Event} event
 */
org.apache.royale.html.beads.layouts.DataGridLayout.prototype.handleLayoutNeeded = function(event) {
  this.layout();
};


/**
 * @copy org.apache.royale.core.IBeadLayout#layout
 * @export
 * @return {boolean}
 */
org.apache.royale.html.beads.layouts.DataGridLayout.prototype.layout = function() {
  var /** @type {org.apache.royale.core.IUIBase} */ header = org.apache.royale.utils.Language.as(this.uiHost.view, org.apache.royale.html.beads.IDataGridView).header;
  var /** @type {org.apache.royale.core.IUIBase} */ listArea = org.apache.royale.utils.Language.as(this.uiHost.view, org.apache.royale.html.beads.IDataGridView).listArea;
  var /** @type {Array} */ displayedColumns = org.apache.royale.utils.Language.as(this.uiHost.view, org.apache.royale.html.beads.IDataGridView).columnLists;
  var /** @type {org.apache.royale.core.IDataGridModel} */ model = org.apache.royale.utils.Language.as(this.uiHost.model, org.apache.royale.core.IDataGridModel);
  var /** @type {org.apache.royale.geom.Rectangle} */ borderMetrics = org.apache.royale.utils.CSSContainerUtils.getBorderMetrics(this._strand);
  var /** @type {number} */ useWidth = this.uiHost.width - (borderMetrics.left + borderMetrics.right);
  var /** @type {number} */ useHeight = this.uiHost.height - (borderMetrics.top + borderMetrics.bottom);
  var /** @type {number} */ xpos = 0;
  var /** @type {number} */ defaultColumnWidth = useWidth / model.columns.length;
  var /** @type {Array} */ columnWidths = [];
  for (var /** @type {number} */ i = 0; i < displayedColumns.length; i++) {
    var /** @type {org.apache.royale.html.supportClasses.IDataGridColumn} */ columnDef = org.apache.royale.utils.Language.as(model.columns[i], org.apache.royale.html.supportClasses.IDataGridColumn);
    var /** @type {org.apache.royale.core.UIBase} */ columnList = org.apache.royale.utils.Language.as(displayedColumns[i], org.apache.royale.core.UIBase);
    columnList.x = xpos;
    columnList.y = 0;
    var /** @type {number} */ columnWidth = defaultColumnWidth;
    if (!isNaN(columnDef.columnWidth)) {
      columnWidth = (columnDef.columnWidth / this.uiHost.width) * useWidth;
    }
    columnList.width = columnWidth;
    columnWidths.push(columnWidth);
    xpos += columnList.width;
  }
  var /** @type {org.apache.royale.html.beads.models.ButtonBarModel} */ bbmodel = org.apache.royale.utils.Language.as(header.getBeadByType(org.apache.royale.html.beads.models.ButtonBarModel), org.apache.royale.html.beads.models.ButtonBarModel);
  bbmodel.buttonWidths = columnWidths;
  header.x = borderMetrics.left;
  header.y = borderMetrics.top;
  
  org.apache.royale.utils.Language.as(header, org.apache.royale.core.UIBase).percentWidth = 100;
  listArea.x = borderMetrics.left;
  listArea.y = header.height + header.y;
  
  org.apache.royale.utils.Language.as(listArea, org.apache.royale.core.UIBase).percentWidth = 100;
  listArea.height = useHeight - header.height;
  header.dispatchEvent(new org.apache.royale.events.Event("layoutNeeded"));
  listArea.dispatchEvent(new org.apache.royale.events.Event("layoutNeeded"));
  return true;
};


org.apache.royale.html.beads.layouts.DataGridLayout.prototype.set__strand = function(value) {
  this._strand = value;
  org.apache.royale.utils.Language.as(this._strand, org.apache.royale.events.IEventDispatcher).addEventListener("widthChanged", org.apache.royale.utils.Language.closure(this.handleSizeChanges, this, 'handleSizeChanges'));
  org.apache.royale.utils.Language.as(this._strand, org.apache.royale.events.IEventDispatcher).addEventListener("heightChanged", org.apache.royale.utils.Language.closure(this.handleSizeChanges, this, 'handleSizeChanges'));
  org.apache.royale.utils.Language.as(this._strand, org.apache.royale.events.IEventDispatcher).addEventListener("sizeChanged", org.apache.royale.utils.Language.closure(this.handleSizeChanges, this, 'handleSizeChanges'));
  org.apache.royale.utils.Language.as(this._strand, org.apache.royale.events.IEventDispatcher).addEventListener("layoutNeeded", org.apache.royale.utils.Language.closure(this.handleLayoutNeeded, this, 'handleLayoutNeeded'));
};


org.apache.royale.html.beads.layouts.DataGridLayout.prototype.get__host = function() {
  return org.apache.royale.utils.Language.as(this._strand, org.apache.royale.core.IUIBase);
};


org.apache.royale.html.beads.layouts.DataGridLayout.prototype.get__uiHost = function() {
  return org.apache.royale.utils.Language.as(this._strand, org.apache.royale.core.UIBase);
};


Object.defineProperties(org.apache.royale.html.beads.layouts.DataGridLayout.prototype, /** @lends {org.apache.royale.html.beads.layouts.DataGridLayout.prototype} */ {
/**
  * @export
  * @type {org.apache.royale.core.IStrand} */
strand: {
set: org.apache.royale.html.beads.layouts.DataGridLayout.prototype.set__strand},
/**
  * @export
  * @type {org.apache.royale.core.IUIBase} */
host: {
get: org.apache.royale.html.beads.layouts.DataGridLayout.prototype.get__host},
/**
  * @export
  * @type {org.apache.royale.core.UIBase} */
uiHost: {
get: org.apache.royale.html.beads.layouts.DataGridLayout.prototype.get__uiHost}}
);


/**
 * Metadata
 *
 * @type {Object.<string, Array.<Object>>}
 */
org.apache.royale.html.beads.layouts.DataGridLayout.prototype.ROYALE_CLASS_INFO = { names: [{ name: 'DataGridLayout', qName: 'org.apache.royale.html.beads.layouts.DataGridLayout', kind: 'class' }], interfaces: [org.apache.royale.core.IBeadLayout] };



/**
 * Reflection
 *
 * @return {Object.<string, Function>}
 */
org.apache.royale.html.beads.layouts.DataGridLayout.prototype.ROYALE_REFLECTION_INFO = function () {
  return {
    variables: function () {return {};},
    accessors: function () {
      return {
        'strand': { type: 'org.apache.royale.core.IStrand', access: 'writeonly', declaredBy: 'org.apache.royale.html.beads.layouts.DataGridLayout'}
      };
    },
    methods: function () {
      return {
        'DataGridLayout': { type: '', declaredBy: 'org.apache.royale.html.beads.layouts.DataGridLayout'},
        'layout': { type: 'Boolean', declaredBy: 'org.apache.royale.html.beads.layouts.DataGridLayout'}
      };
    }
  };
};