/**
 * Generated by Apache Royale Compiler from org/apache/royale/reflection/getDefinitionByName.as
 * org.apache.royale.reflection.getDefinitionByName
 *
 * @fileoverview
 *
 * @suppress {missingRequire|checkTypes|accessControls}
 */

goog.provide('org.apache.royale.reflection.getDefinitionByName');
/* Royale Dependency List: org.apache.royale.reflection.ExtraData*/




/**
 *  The equivalent of flash.utils.getDefinitionByName.
 * 
 *  @langversion 3.0
 *  @playerversion Flash 10.2
 *  @playerversion AIR 2.6
 *  @productversion Royale 0.0
 * @param {string} name
 * @return {*}
 */
org.apache.royale.reflection.getDefinitionByName = function(name) {
  
  var /** @type {Array} */ parts = name.split('.');
  var /** @type {Object} */ o;
  if (parts[0] != 'Vector') {
    var /** @type {number} */ n = (parts.length) >> 0;
    o = goog.global;
    for (var /** @type {number} */ i = 0; i < n; i++) {
      if (!o)
        break;
      o = o[parts[i]];
    }
  } else {
    if (parts[1] != '<*>') {
      if (!org.apache.royale.reflection.ExtraData.hasData(name)) {
        if (org.apache.royale.reflection.ExtraData.hasData('Vector.<*>')) {
          
/**
 * @const
 * @type {Object}
 */
var newVectorData = org.apache.royale.reflection.ExtraData.getData('Vector.<*>')['variant'](name);
          org.apache.royale.reflection.ExtraData.addExternDefintion(newVectorData);
          o = newVectorData['classRef'];
        }
      } else {
        o = org.apache.royale.reflection.ExtraData.getData(name)['classRef'];
      }
    }
  }
  if (o == null && org.apache.royale.reflection.ExtraData.hasData(name))
    o = org.apache.royale.reflection.ExtraData.getData(name)['classRef'];
  if (o == null) {
    if (name == 'undefined')
      return undefined;
    throw new ReferenceError('Error #1065: Variable ' + name + ' is not defined.');
  }
  return o;
}
